#version 460

#include "include/defines.glsl"

struct Light {
    vec3 normal;  
    vec3 intensity;
};

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_shadowmap;

layout(std430, set = 1, binding = 0) buffer BinCounters {
    uint bin_counters[];
};
layout(std430, set = 1, binding = 1) buffer BinOffsets {
    uint bin_offsets[];
};
layout(std430, set = 1, binding = 2) buffer Bins {
    Light bins[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size;
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};
layout(std140, set = 2, binding = 1) uniform AssignUBO {
    mat4 inverse_vp_matrix;
    vec4 light_direction;
    vec4 light_intensity;
    uint mode;
};

#include "include/voxel_utils.glsl"

vec3 worldPos(vec2 uv, float depth) {
    vec4 ndc = vec4(
        2.0 * uv.x - 1.0,
        1.0 - 2.0 * uv.y,
        depth,
        1.0
    );
    vec4 world_pos = inverse_vp_matrix * ndc;
    world_pos /= world_pos.w;
    return world_pos.xyz;
}

void main() {
    ivec2 shadowmap_size = textureSize(u_shadowmap, 0);    
    ivec2 global_id = ivec2(gl_GlobalInvocationID.xy);
    if (global_id.x > 2 * shadowmap_size.x || global_id.y > 2 * shadowmap_size.y) return;

    float depth00 = texelFetch(u_shadowmap, 2 * global_id + ivec2(0, 0), 0).r;
    float depth01 = texelFetch(u_shadowmap, 2 * global_id + ivec2(0, 1), 0).r;
    float depth10 = texelFetch(u_shadowmap, 2 * global_id + ivec2(1, 0), 0).r;
    float depth11 = texelFetch(u_shadowmap, 2 * global_id + ivec2(1, 1), 0).r;
    vec2 uv00 = vec2(2 * global_id + ivec2(0, 0)) / vec2(shadowmap_size - 1);
    vec2 uv01 = vec2(2 * global_id + ivec2(0, 1)) / vec2(shadowmap_size - 1);
    vec2 uv10 = vec2(2 * global_id + ivec2(1, 0)) / vec2(shadowmap_size - 1);
    vec2 uv11 = vec2(2 * global_id + ivec2(1, 1)) / vec2(shadowmap_size - 1);
    vec3 world00 = worldPos(uv00, depth00);
    vec3 world01 = worldPos(uv01, depth01);
    vec3 world10 = worldPos(uv10, depth10);
    vec3 world11 = worldPos(uv11, depth11);
    vec3 world = 0.25 * (world00 + world01 + world10 + world11);
    
    if (mode == 0) {
        ivec3 cascade_size_half = ivec3(cascade_size.xyz / 2);
        for (int i = 0; i < n_cascades; ++i) {
            float voxel_size = voxelSize(i);
            ivec3 voxel_pos = ivec3(floor((world - anchors[i].xyz) / voxel_size));
            if (voxel_pos.x < -cascade_size_half.x || voxel_pos.x >= cascade_size_half.x ||
                voxel_pos.y < -cascade_size_half.y || voxel_pos.y >= cascade_size_half.y ||
                voxel_pos.z < -cascade_size_half.z || voxel_pos.z >= cascade_size_half.z) continue;
            uint index = indexFromCascadePos(i, voxel_pos);
            atomicAdd(bin_offsets[index], 1);
        }
        
    } else if (mode == 1) {
        // recomputing this is kinda expensive?
        ivec3 cascade_size_half = ivec3(cascade_size.xyz / 2);
        for (int i = 0; i < n_cascades; ++i) {
            float voxel_size = voxelSize(i);
            ivec3 voxel_pos = ivec3(floor((world - anchors[i].xyz) / voxel_size));
            if (voxel_pos.x < -cascade_size_half.x || voxel_pos.x >= cascade_size_half.x ||
                voxel_pos.y < -cascade_size_half.y || voxel_pos.y >= cascade_size_half.y ||
                voxel_pos.z < -cascade_size_half.z || voxel_pos.z >= cascade_size_half.z) continue;
            uint index = indexFromCascadePos(i, voxel_pos);
            vec3 dx = world10 + world11 - world00 - world01;
            vec3 dy = world01 + world11 - world00 - world10;
            vec3 normal = normalize(cross(dy, dx));
            uint slot = atomicAdd(bin_counters[index], 1);
            bins[bin_offsets[index] + slot] = Light(
                normal,
                light_intensity.rgb * max(0.0, dot(light_direction.xyz, normal))
            );
        }
    }
    
}
