#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(set = 0, binding = 0) uniform usampler3D target_weight_coverage;
layout(set = 0, binding = 1) uniform usampler3D target_diffuse_emissive_r;
layout(set = 0, binding = 2) uniform usampler3D target_diffuse_emissive_g;
layout(set = 0, binding = 3) uniform usampler3D target_diffuse_emissive_b;
layout(set = 0, binding = 4) uniform usampler3D target_normal_xy;
layout(set = 0, binding = 5) uniform usampler3D target_normal_z_pad;

layout(r16, set = 1, binding = 0) uniform image3D cascades_coverage;
layout(rgba8, set = 1, binding = 1) uniform image3D cascades_diffuse;
layout(r11f_g11f_b10f, set = 1, binding = 2) uniform image3D cascades_emissive;
layout(rgba8_snorm, set = 1, binding = 3) uniform image3D cascades_normal;

layout(std140, set = 2, binding = 0) uniform AverageData {
    uint ix_temporal;
    uint ix_cascade;
} average_data;

void main() {
    ivec3 voxel_pos = ivec3(gl_GlobalInvocationID);

    vec2 weight_coverage = unpackHalf2x16(texelFetch(target_weight_coverage, voxel_pos, 0).r);
    vec2 diffuse_emissive_r = unpackHalf2x16(texelFetch(target_diffuse_emissive_r, voxel_pos, 0).r);
    vec2 diffuse_emissive_g = unpackHalf2x16(texelFetch(target_diffuse_emissive_g, voxel_pos, 0).r);
    vec2 diffuse_emissive_b = unpackHalf2x16(texelFetch(target_diffuse_emissive_b, voxel_pos, 0).r);
    vec2 normal_xy = unpackHalf2x16(texelFetch(target_normal_xy, voxel_pos, 0).r);
    vec2 normal_z_pad = unpackHalf2x16(texelFetch(target_normal_z_pad, voxel_pos, 0).r);

    float iweight = 1.0 / weight_coverage.x;
    float coverage = clamp(weight_coverage.y, 0.0, 1.0);
    vec3 diffuse = vec3(diffuse_emissive_r.x, diffuse_emissive_g.x, diffuse_emissive_b.x);
    vec3 emissive = vec3(diffuse_emissive_r.y, diffuse_emissive_g.y, diffuse_emissive_b.y);
    vec3 normal = vec3(normal_xy, normal_z_pad.x);

    diffuse *= iweight;
    emissive *= iweight;
    normal = normalize(normal * iweight);

    imageStore(
        cascades_coverage,
        voxel_pos + ivec3(64 * average_data.ix_cascade, 64 * average_data.ix_temporal, 0),
        vec4(coverage, 0.0, 0.0, 0.0)
    );
    imageStore(
        cascades_diffuse,
        voxel_pos + ivec3(64 * average_data.ix_cascade, 0, 0),
        vec4(diffuse, coverage)
    );
    imageStore(
        cascades_emissive,
        voxel_pos + ivec3(64 * average_data.ix_cascade, 0, 0),
        vec4(emissive, coverage)
    );
    imageStore(
        cascades_normal,
        voxel_pos + ivec3(64 * average_data.ix_cascade, 0, 0),
        vec4(normal, coverage)
    );
}
