#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer OpacityTargets {
    uint opacity_targets[];
};
layout(std430, set = 0, binding = 1) readonly buffer DiffuseTargets {
    uint diffuse_targets[];
};
layout(std430, set = 0, binding = 2) readonly buffer OldOpacityCascades {
    float old_opacity_cascades[];
};
layout(std430, set = 0, binding = 3) readonly buffer OldDiffuseCascades {
    uint old_diffuse_cascades[];
};

layout(std430, set = 1, binding = 0) buffer NewOpacityCascades {
    float new_opacity_cascades[];
};
layout(std430, set = 1, binding = 1) buffer NewDiffuseCascades {
    uint new_diffuse_cascades[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform AverageUBO {
    vec4 old_anchor; // xyz
    vec4 new_anchor; // xyz
    float half_life;
};

#include "include/voxel_utils.glsl"

int floorDiv2(int x) {
    return x >= 0 ? x / 2 : (x - 1) / 2;
}
ivec3 floorDiv2(ivec3 v) {
    return ivec3(
        floorDiv2(v.x),
        floorDiv2(v.y),
        floorDiv2(v.z)
    );
}

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    if (global_id >= n_cascades * cascade_size[3]) return;
    
    // TODO actually test whether reprojection improves visual outcome
    new_opacity_cascades[global_id] = float(bitCount(opacity_targets[global_id])) / 32.0;
    new_diffuse_cascades[global_id] =
        packUnorm4x8(vec4(unpackDiffuse(diffuse_targets[global_id]), 0.0));
    
    // uint cascade = indexToCascade(global_id);
    // ivec3 voxel_pos = indexToPos(global_id);
    // vec3 anchor_move = (new_anchor.xyz - old_anchor.xyz) / voxelSize(cascade);
    // ivec3 reprojected_pos = voxel_pos + ivec3(round(anchor_move));
    // uint reprojected_cascade = cascade;

    // // could probably optimize this to not use a loop
    // while (reprojected_pos.x < -int(cascade_size.x) / 2 ||
    //        reprojected_pos.x >= int(cascade_size.x) / 2 ||
    //        reprojected_pos.y < -int(cascade_size.y) / 2 ||
    //        reprojected_pos.y >= int(cascade_size.y) / 2 ||
    //        reprojected_pos.z < -int(cascade_size.z) / 2 ||
    //        reprojected_pos.z >= int(cascade_size.z) / 2) {
    //     reprojected_pos = floorDiv2(reprojected_pos);
    //     reprojected_cascade += 1;
    // }

    // float old_opacity = 0;
    // vec3 old_diffuse = vec3(0.0, 0.0, 0.0);
    // if (reprojected_cascade < n_cascades) {
    //     uint reprojected_index = indexFromCascadePos(reprojected_cascade, reprojected_pos);
    //     old_opacity = old_opacity_cascades[reprojected_index];
    //     old_diffuse = unpackUnorm4x8(old_diffuse_cascades[reprojected_index]).rgb;
    // }
    // float new_opacity = float(bitCount(opacity_targets[global_id])) / 32.0;
    // vec3 new_diffuse = unpackDiffuse(diffuse_targets[global_id]);

    // // we might want to use a slower fade for color
    // float alpha = 1.0 - pow(0.5, 1.0 / (half_life * float(1 << cascade / 2)));

    // float mixed_opacity = mix(old_opacity, new_opacity, alpha);
    // if (mixed_opacity < 0.01) mixed_opacity = 0.0;
    // new_opacity_cascades[global_id] = mixed_opacity;
    
    // vec3 mixed_diffuse;
    // if (new_opacity > 0) {
    //     if (old_opacity > 0) {
    //         mixed_diffuse = mix(old_diffuse, new_diffuse, alpha);
    //     } else {
    //         mixed_diffuse = new_diffuse;
    //     }
    // } else {
    //     mixed_diffuse = old_diffuse;
    // }
    // new_diffuse_cascades[global_id] = packUnorm4x8(vec4(mixed_diffuse, 0.0));
}
