#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer VoxelTargets {
    uint voxel_targets[];
};
layout(std430, set = 0, binding = 1) readonly buffer VisibilityTargets {
    uint visibility_targets[];
};

layout(rgba16f, set = 1, binding = 0) uniform image3D u_old_energy_cascades;
layout(rgba16f, set = 1, binding = 1) uniform image3D u_new_energy_cascades;

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform UpdateUBO {
    vec4 anchor_moves[MAX_CASCADES];
    vec4 light_direction;
    vec4 light_energy;
};

#include "include/voxel_utils.glsl"

float blend_rate_modifier = 0.0625;
float blend_rates[MAX_CASCADES] = {
    6.145e-01, 6.145e-01,
    3.542e-01, 3.542e-01,
    1.902e-01, 1.902e-01,
    1.902e-01, 1.902e-01
};

int floorDiv2(int x) {
    return x >= 0 ? x / 2 : (x - 1) / 2;
}

ivec3 floorDiv2(ivec3 v) {
    return ivec3(
        floorDiv2(v.x),
        floorDiv2(v.y),
        floorDiv2(v.z)
    );
}

const float PI = 3.141592653589793;
const float sqrt_3_over_4pi = sqrt(3.0/(4.0 * PI));
const float inv_sqrt_4pi = 1.0 / sqrt(4.0 * PI);

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    if (global_id >= n_cascades * cascade_size[3]) return;

    uint cascade = indexToCascade(global_id);
    float voxel_size = voxelSize(cascade);
    ivec3 voxel_pos = indexToPos(global_id);
    vec3 anchor_move = anchor_moves[cascade].xyz / voxelSize(cascade);
    ivec3 reprojected_pos = voxel_pos + ivec3(round(anchor_move));
    uint reprojected_cascade = cascade;
    while (reprojected_pos.x < -int(cascade_size.x) / 2 ||
           reprojected_pos.x >= int(cascade_size.x) / 2 ||
           reprojected_pos.y < -int(cascade_size.y) / 2 ||
           reprojected_pos.y >= int(cascade_size.y) / 2 ||
           reprojected_pos.z < -int(cascade_size.z) / 2 ||
           reprojected_pos.z >= int(cascade_size.z) / 2) {
        reprojected_pos = floorDiv2(reprojected_pos);
        reprojected_cascade += 1;
    }

    ivec3 image_pos = voxel_pos + 
                      ivec3(cascade_size.xyz / 2) +
                      ivec3(cascade * cascade_size[0], 0, 0);
    ivec3 reprojected_image_pos = reprojected_pos + 
                                  ivec3(cascade_size.xyz / 2) +
                                  ivec3(reprojected_cascade * cascade_size[0], 0, 0);

    uint packed = voxel_targets[global_id];
    float visibility = unpackUnorm4x8(visibility_targets[global_id]).r;
    vec3 normal = unpackNormal(packed);
    normal *= sign(normal) * sign(-light_direction.xyz);
    
    // NOTE to support coloured lighting we have to do this and the color blend step simultaneously
    float overall_intensity = 0.33 * (light_energy.r + light_energy.g + light_energy.b);
    float intensity = visibility;// * overall_intensity / pow(6.0 * voxel_size, 2.0);
    vec4 energy = intensity * vec4(0.5 * sqrt_3_over_4pi * normal, inv_sqrt_4pi);
    // vec4 energy = intensity * vec4(0.0, 0.0, 0.0, inv_sqrt_4pi);
    // vec4 energy = vec4(0.0, 0.0, 0.0, max(dot(normal, -light_direction.xyz), 0.0) * visibility);

    if (reprojected_cascade >= n_cascades) {
        vec4 mixed = mix(vec4(0.0), energy, blend_rate_modifier * blend_rates[cascade]);
        // if (dot(mixed, mixed) < 0.001) mixed = vec4(0.0);
        imageStore(u_new_energy_cascades, image_pos, mixed);
    } else {
        vec4 old = imageLoad(u_old_energy_cascades, reprojected_image_pos);
        vec4 mixed = mix(old, energy, blend_rate_modifier * blend_rates[cascade]);
        // if (dot(mixed, mixed) < 0.001) mixed = vec4(0.0);
        imageStore(u_new_energy_cascades, image_pos, mixed);
    }
}
