#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(r32ui, set = 1, binding = 0) uniform uimage3D u_opacity_targets;
layout(r32ui, set = 1, binding = 1) uniform uimage3D u_radiance_targets;

void main() {
    ivec3 texcoords = ivec3(gl_GlobalInvocationID);
    if (texcoords.x < 132 &&
        texcoords.y < 66 &&
        texcoords.z < 66) {
        imageStore(u_opacity_targets, texcoords, uvec4(0, 0, 0, 0));
    }
    if (texcoords.x < 528 &&
        texcoords.y < 396 &&
        texcoords.z < 132) {
        imageStore(u_radiance_targets, texcoords, uvec4(0, 0, 0, 0));
    }
}
