#version 460

layout(r32ui, set = 1, binding = 0) uniform uimage3D cascades;

layout(std140, set = 2, binding = 0) uniform ClearData {
    uint ix_cascade;
} clear_data;

void main() {
    for (int x = 0; x < 64; ++x) {
        for (int y = 0; y < 64; ++y) {
            for (int z = 0; z < 64; ++z) {
                imageStore(cascades, ivec3(x + 64 * clear_data.ix_cascade, y, z), uvec4(0));
            }
        }
    }
}
