#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform usampler2D u_shadowmap;

layout(std430, set = 1, binding = 0) buffer BinCounters {
    uint bin_counters[];
};

layout(std140, set = 2, binding = 0) uniform VoxelizeUBO {
    mat4 model_matrix;
    vec4 diffuse; // rgb 0-1
    vec4 emissive; // rgb 0-inf
    uint target_cascade;
    uint n_triangles;
    uint first_index;
    uint first_vertex;
};
layout(std140, set = 2, binding = 1) uniform InjectUBO {
    mat4 light_matrix;
    float light_intensity;
};

void main() {}
