#version 460

#include "include/defines.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer OpacityCascades {
    float opacity_cascades[];
};
layout(std430, set = 0, binding = 1) readonly buffer DiffuseCascades {
    uint diffuse_cascades[];
};

layout(rgba16f, set = 1, binding = 0) uniform image2D u_color_target;

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform DebugUBO {
    mat4 camera_view_matrix_inv;
    mat4 camera_projection_matrix_inv;
    uint debug_view;
};

#include "include/voxel_utils.glsl"

float voxelAt(vec3 pos) {
    uint cascade = cascadeAt(pos);
    if (cascade >= n_cascades) return 0.0;
    float voxel_size = voxelSize(cascade);
    ivec3 voxel_pos = ivec3(floor((pos - anchors[cascade].xyz) / voxel_size));
    return opacity_cascades[indexFromCascadePos(cascade, voxel_pos)];
}

vec4 voxelAt2(vec3 pos) {
    uint cascade = cascadeAt(pos);
    if (cascade >= n_cascades) return vec4(0.0);
    float voxel_size = voxelSize(cascade);
    ivec3 voxel_pos = ivec3(floor((pos - anchors[cascade].xyz) / voxel_size));
    float opacity = opacity_cascades[indexFromCascadePos(cascade, voxel_pos)];
    vec4 diffuse = unpackUnorm4x8(diffuse_cascades[indexFromCascadePos(cascade, voxel_pos)]);
    return vec4(diffuse.rgb, opacity);
}

const vec3 cascade_colors[8] = {
    vec3(1.0, 1.0, 1.0),
    vec3(1.0, 1.0, 0.0),
    vec3(1.0, 0.0, 1.0),
    vec3(0.0, 1.0, 1.0),
    vec3(1.0, 0.0, 0.0),
    vec3(0.0, 1.0, 0.0),
    vec3(0.0, 0.0, 1.0),
    vec3(0.0, 0.0, 0.0),
};

void main() {
    ivec2 global_id = ivec2(gl_GlobalInvocationID.xy);
    if (global_id.x >= 640 || global_id.y >= 360) return;

    vec2 uv = vec2(global_id) / vec2(640.0 - 1.0, 360.0 - 1.0);
    uv = 2.0 * vec2(uv.x, 1.0 - uv.y) - 1.0;

    vec4 near = camera_projection_matrix_inv * vec4(uv, -1.0, 1.0);
    vec4 far = camera_projection_matrix_inv * vec4(uv, 1.0, 1.0);
    near /= near.w;
    far /= far.w;
    vec3 src = (camera_view_matrix_inv * vec4(near.xyz, 1.0)).xyz;
    vec3 dst = (camera_view_matrix_inv * vec4(far.xyz, 1.0)).xyz;
    vec3 ray_origin = (camera_view_matrix_inv * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
    vec3 ray_dir = normalize(dst - src); 
    
    vec4 o_color = vec4(0.5 * ray_dir + 0.5, 1.0);
    vec3 pos = ray_origin;
    vec4 acc = vec4(0.0, 0.0, 0.0, 0.0);

    if (debug_view == 0) {
    
        float d = 0.0;
        float step = min_voxel_size * 0.25;
        for (int i = 0; i < 1024; ++i) {
            d += step;
            pos += step * ray_dir;
            step *= 1.01;
            float occlusion = voxelAt(pos);
            vec3 voxel_color = cascade_colors[cascadeAt(pos) % 8];
            voxel_color = voxel_color * max(exp(-d*0.1), 0.01);
            acc.rgb += voxel_color * occlusion * (1.0 - acc.a);
            acc.a += occlusion * (1.0 - acc.a);

            if (acc.a > 0.99) break;
        }

    } else if (debug_view == 1) {

        float step = min_voxel_size * 0.25;
        for (int i = 0; i < 1024; ++i) {
            pos += step * ray_dir;
            step *= 1.01;
            vec4 voxel_color = voxelAt2(pos);
            acc.rgb += 0.5 * voxel_color.rgb * voxel_color.a * (1.0 - acc.a);
            acc.a += voxel_color.a * (1.0 - acc.a);

            if (acc.a > 0.99) break;
        }
        
    }

    o_color = (1.0 - acc.a) * o_color + acc.a * acc;
    imageStore(u_color_target, global_id, o_color);
}
