#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_depth;

layout(r32f, set = 1, binding = 0) uniform image2D u_downsampled_depth;
layout(rg16f, set = 1, binding = 1) uniform image2D u_downsampled_normals;

layout(std140, set = 2, binding = 0) uniform DownsampleUBO {
    mat4 inverse_vp_matrix;
};

#include "include/octahedral.glsl"

vec3 worldPos(vec2 uv, float depth) {
    vec4 ndc = vec4(
        2.0 * uv.x - 1.0,
        1.0 - 2.0 * uv.y,
        depth,
        1.0
    );
    vec4 world_pos = inverse_vp_matrix * ndc;
    world_pos /= world_pos.w;
    return world_pos.rgb;
}

void main() {
    // honestly, just writing the normals during the preass is gonna be better, this is silly
    ivec2 depth_size = textureSize(u_depth, 0);    
    ivec2 global_id = ivec2(gl_GlobalInvocationID.xy);
    if (global_id.x >= depth_size.x || global_id.y >= depth_size.y) return;

    float depth00 = texelFetch(u_depth, 2 * global_id + ivec2(0, 0), 0).r;
    float depth01 = texelFetch(u_depth, 2 * global_id + ivec2(0, 1), 0).r;
    float depth10 = texelFetch(u_depth, 2 * global_id + ivec2(1, 0), 0).r;
    float depth11 = texelFetch(u_depth, 2 * global_id + ivec2(1, 1), 0).r;

    vec2 uv00 = vec2(2 * global_id + ivec2(0, 0)) / vec2(depth_size - 1);
    vec2 uv01 = vec2(2 * global_id + ivec2(0, 1)) / vec2(depth_size - 1);
    vec2 uv10 = vec2(2 * global_id + ivec2(1, 0)) / vec2(depth_size - 1);
    vec2 uv11 = vec2(2 * global_id + ivec2(1, 1)) / vec2(depth_size - 1);
    vec3 world00 = worldPos(uv00, depth00);
    vec3 world01 = worldPos(uv01, depth01);
    vec3 world10 = worldPos(uv10, depth10);
    vec3 world11 = worldPos(uv11, depth11);

    // might be better to pick one than to average
    float depth = 0.25 * (depth00 + depth01 + depth10 + depth11);
    vec3 dx = world10 + world11 - world00 - world01;
    vec3 dy = world01 + world11 - world00 - world10;
    vec3 normal = normalize(cross(dy, dx));

    imageStore(u_downsampled_depth, global_id, vec4(depth, 0.0, 0.0, 0.0));   
    imageStore(u_downsampled_normals, global_id, vec4(encodeOctahedral(normal), 0.0, 0.0));   
}
