#version 460

#define MIN_VOXEL_SIZE 0.244140625

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_lowres_depth;
layout(set = 0, binding = 1) uniform sampler2D u_lowres_normal;
layout(set = 0, binding = 2) uniform sampler3D u_opacity_cascades;
layout(set = 0, binding = 3) uniform sampler3D u_radiance_cache_cascades;

layout(rgba16f, set = 1, binding = 0) uniform image2D u_lowres_indirect_light;

layout(std140, set = 2, binding = 0) uniform UBO {
    mat4 inverse_vp_matrix;
    float cone_step_factor;
    float cone_scale_factor;
};

float absmax(vec3 v) {
    vec3 a = abs(v);
    return max(max(a.x, a.y), a.z);
}

uint cascadeAt(vec3 pos) {
    float maximum = absmax(pos);
    return uint(clamp(ceil(log2(maximum / (MIN_VOXEL_SIZE * 32))), 0, 8));
}

float voxelSize(uint cascade) {
    return MIN_VOXEL_SIZE * float(1 << cascade);
}

bool inBounds(vec3 position) {
    return absmax(position) <= 1000.0;
}

vec4 sampleRadianceAt(vec3 position, vec3 dir, uint cascade) {
    float cascade_world_size = 66.0 * MIN_VOXEL_SIZE * float(1 << cascade);
    vec3 uvw = position / cascade_world_size + 0.5;
    vec3 faces = vec3(
        (dir.x > 0) ? 1 : 0,  
        (dir.y > 0) ? 3 : 2,  
        (dir.z > 0) ? 5 : 4  
    );
    vec3 weights = abs(dir) / (abs(dir.x) + abs(dir.y) + abs(dir.z));
    // vec3 weights = dir * dir;
    return
        weights[0] * texture(u_radiance_cache_cascades, vec3(
            0.125 * (uvw.x + float(cascade)),
            (1.0 / 6.0) * (uvw.y + faces[0]),
            uvw.z
        )) +
        weights[1] * texture(u_radiance_cache_cascades, vec3(
            0.125 * (uvw.x + float(cascade)),
            (1.0 / 6.0) * (uvw.y + faces[1]),
            uvw.z
        )) +
        weights[2] * texture(u_radiance_cache_cascades, vec3(
            0.125 * (uvw.x + float(cascade)),
            (1.0 / 6.0) * (uvw.y + faces[2]),
            uvw.z
        ));
}

vec4 sampleRadianceAtDiameter(vec3 position, vec3 dir, float diameter) {
    float fcascade = clamp(log2(diameter / MIN_VOXEL_SIZE), 0, 7);
    uint low_cascade = uint(fcascade);
    uint high_cascade = min(low_cascade + 1, 7);
    float frac = fract(fcascade);
    vec4 low = sampleRadianceAt(position, dir, low_cascade);
    vec4 high = sampleRadianceAt(position, dir, high_cascade);
    return (1 - frac) * low + frac * high;
}

vec4 gatherRadiance(vec3 origin, vec3 normal, vec3 dir, bool skip) {
    float diameter = clamp(
        0.5 * MIN_VOXEL_SIZE * absmax(origin),
        MIN_VOXEL_SIZE,
        MIN_VOXEL_SIZE * 128
    );

    // TODO see if we could improve on this
    // 2.6 > 1.5 * sqrt(3)
    // so even if we are at the corner of a voxel moving diagonally through
    // we'll never sample the voxel we're starting in
    const float initial_step = 2.0 / absmax(normal);
    origin += normal * diameter * initial_step;
    float d = diameter * initial_step;

    vec4 acc = vec4(0.0, 0.0, 0.0, 0.0);
    float occlusion = 0.0;
    while (acc.a < 0.95 && inBounds(origin) && diameter < 32.0) {
        vec4 rad = sampleRadianceAtDiameter(origin, dir, diameter);
        if (skip) {
            skip = false;
        } else {
            acc.rgb += (1 - acc.a) * rad.a * rad.rgb / (1.0 + 0.25 * diameter);
            acc.a += (1 - acc.a) * rad.a;
            if (occlusion < 1.0) {
                occlusion += ((1.0 - occlusion) * rad.a) / (1.0 + 2 * diameter * diameter);
            }
        }
        // acc.a += (1 - acc.a) * rad.a;
        d += diameter;
        origin += cone_step_factor * dir * diameter;
        diameter = cone_scale_factor * diameter;
    }

    return vec4(acc.rgb, clamp(occlusion, 0.0, 1.0));
}

// https://www.reedbeta.com/blog/hash-functions-for-gpu-rendering/
uint pcg_hash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

// vec3 diffuse_cones[6] = {
//     // basically, one cone up surrounded by five cones
//     // but it's all slightly off angle, so that all gaps get filled when randomly rotated
//     // at the cost of less coverage for very low angles
//     vec3(0.0, 0.9659258262890683, 0.25881904510252074),
//     vec3(0.7660444431189781, 0.6208851530148457, 0.16636567534280192),
//     vec3(0.236720751370257, 0.4323221341029862, 0.8700924423504325),
//     vec3(-0.619742972929746, 0.5043467983060274, 0.6012927361465958),
//     vec3(-0.6197429729297461, 0.7374235077236639, -0.2685613854609918),
//     vec3(0.23672075137025683, 0.8094481719267052, -0.5373610916648287),
// };

vec3 diffuse_cones[9] = {
    // nine cones spread fairly evenly, no tilt
    vec3(0.39874906892524625, 0.917060074385124, 0.0),
    vec3(-0.19937453446262304, 0.917060074385124, 0.34532682342465537),
    vec3(-0.1993745344626233, 0.917060074385124, -0.34532682342465526),
    vec3(0.3715724127386972, 0.6691306063588582, 0.6435822975543765),
    vec3(-0.7431448254773942, 0.6691306063588582, 9.100899318238092e-17),
    vec3(-0.37157241273869746, 0.6691306063588582, -0.6435822975543763),
    vec3(0.898794046299167, 0.4383711467890774, 0.0),
    vec3(-0.4493970231495833, 0.4383711467890774, 0.7783784768652856),
    vec3(-0.4493970231495839, 0.4383711467890774, -0.7783784768652854),
};

// vec3 diffuse_cones[20] = {
//     vec3(0.6087614290087207, 0.7933533402912352, 0.0),
//     vec3(0.1881176270836728, 0.7933533402912352, 0.5789665239278933),
//     vec3(-0.4924983415880331, 0.7933533402912352, 0.3578209901358174),
//     vec3(-0.4924983415880332, 0.7933533402912352, -0.35782099013581725),
//     vec3(0.18811762708367266, 0.7933533402912352, -0.5789665239278934),
//     vec3(0.9832549075639546, 0.18223552549214747, 0.0),
//     vec3(0.30384247623983, 0.18223552549214747, 0.9351309870178879),
//     vec3(-0.7954699300218072, 0.18223552549214747, 0.5779427339102915),
//     vec3(-0.7954699300218074, 0.18223552549214747, -0.5779427339102913),
//     vec3(0.3038424762398298, 0.18223552549214747, -0.935130987017888),
//     vec3(0.6087614290087207, -0.7933533402912352, 0.0),
//     vec3(0.1881176270836728, -0.7933533402912352, 0.5789665239278933),
//     vec3(-0.4924983415880331, -0.7933533402912352, 0.3578209901358174),
//     vec3(-0.4924983415880332, -0.7933533402912352, -0.35782099013581725),
//     vec3(0.18811762708367266, -0.7933533402912352, -0.5789665239278934),
//     vec3(0.9832549075639546, -0.18223552549214747, 0.0),
//     vec3(0.30384247623983, -0.18223552549214747, 0.9351309870178879),
//     vec3(-0.7954699300218072, -0.18223552549214747, 0.5779427339102915),
//     vec3(-0.7954699300218074, -0.18223552549214747, -0.5779427339102913),
//     vec3(0.3038424762398298, -0.18223552549214747, -0.935130987017888),
// };

vec3 randomVec(uint seed) {
    // not really uniform, but it's not that important
    uint r = pcg_hash(seed);
    return normalize(vec3(
        float((r >> 0) & 0x3FFu) / 1023.0 - 0.5,
        float((r >> 10) & 0x3FFu) / 1023.0 - 0.5,
        float((r >> 20) & 0x3FFu) / 1023.0 - 0.5
    ));
}

mat3 getAlignmentMatrix(vec3 normal, uint seed) {
    // use the one from learnopengl instead
    vec3 random_vector = randomVec(seed);
    vec3 tangent   = normalize(random_vector - normal * dot(random_vector, normal));
    vec3 bitangent = cross(normal, tangent);
    // return mat3(tangent, bitangent, normal); // original
    return mat3(bitangent, normal, tangent); // seems better?
    // return mat3(tangent, normal, bitangent); // also seems better?
}

// https://jcgt.org/published/0003/02/01/
vec2 signNotZero(vec2 v) {
    return vec2((v.x >= 0.0) ? +1.0 : -1.0, (v.y >= 0.0) ? +1.0 : -1.0);
}
vec2 encodeOctahedral(vec3 v) {
    vec2 p = v.xy * (1.0 / (abs(v.x) + abs(v.y) + abs(v.z)));
    return (v.z <= 0.0) ? ((1.0 - abs(p.yx)) * signNotZero(p)) : p;
}
vec3 decodeOctahedral(vec2 e) {
    vec3 v = vec3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0) v.xy = (1.0 - abs(v.yx)) * signNotZero(v.xy);
    return normalize(v);
}

void main() {
    ivec2 lowres_size = imageSize(u_lowres_indirect_light);
    ivec2 texcoords = ivec3(gl_GlobalInvocationID).xy;
    if (texcoords.x >= lowres_size.x || texcoords.y >= lowres_size.y) return;

    float depth = texelFetch(u_lowres_depth, texcoords, 0).r;
    vec3 normal = decodeOctahedral(texelFetch(u_lowres_normal, texcoords, 0).rg);
    float x_ndc = (float(texcoords.x) + 0.5) / float(lowres_size.x) * 2.0 - 1.0;
    float y_ndc = 1.0 - (float(texcoords.y) + 0.5) / float(lowres_size.y) * 2.0;
    vec4 ndc = vec4(x_ndc, y_ndc, depth, 1.0);
    vec4 world_pos = inverse_vp_matrix * ndc;
    world_pos /= world_pos.w;

    uint seed = uint(texcoords.x) + uint(texcoords.y) * 65536u;
    // vec3 world_pos_norm = clamp((world_pos.xyz + 1111.0) / 2222.0, 0.0, 1.0);
    // uint seed = 505319 * uint(world_pos_norm.x * 1e7) +
    //             671159 * uint(world_pos_norm.y * 1e7) +
    //             377339 * uint(world_pos_norm.z * 1e7);
    vec4 bounced = vec4(0.0, 0.0, 0.0, 0.0);

    mat3 amat = getAlignmentMatrix(normal, seed);
    bounced += gatherRadiance(world_pos.xyz, normal, normalize(amat * diffuse_cones[0]), false);
    for (int i = 1; i < diffuse_cones.length(); ++i) {
        bounced += gatherRadiance(world_pos.xyz, normal, amat * diffuse_cones[i], true);
    }
    bounced.a = 1.0 - (bounced.a / float(diffuse_cones.length()));

    // uint n_samples = 0;
    // for (int i = 1; i < diffuse_cones.length(); ++i) {
    //     if (dot(normal, diffuse_cones[i]) < 0) continue;
    //     bounced += gatherRadiance(world_pos.xyz, normal, diffuse_cones[i], n_samples != 0);
    //     n_samples += 1;
    // }
    // bounced.a = 1.0 - (bounced.a / float(diffuse_cones.length()));

    // vec3 helper = (pcg_hash(seed) % 2 == 0) ? vec3(0.0f, 1.0f, 0.0f) : vec3(0.0f, 0.0f, 1.0f);
    // if (abs(dot(normal, helper)) > 0.9) helper = vec3(0.0f, 0.0f, 1.0f);
    // vec3 right = normalize(helper - dot(normal, helper) * normal);
    // vec3 up = cross(right, normal);
    // for (int i = 1; i < diffuse_cones.length(); ++i) {
    //     vec3 dir = normal;
    //     dir += diffuse_cones[i].x * right + diffuse_cones[i].z * up;
    //     dir = normalize(dir);
    //     bounced += gatherRadiance(world_pos.xyz, normal, dir, i != 0);
    // }
    // bounced.a = 1.0 - (bounced.a / float(diffuse_cones.length()));

    imageStore(u_lowres_indirect_light, texcoords, bounced);
}
