#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_lowres_depth;
layout(set = 0, binding = 1) uniform sampler2D u_lowres_normal;

layout(rgba16f, set = 1, binding = 0) uniform image2D u_lowres_indirect_light;

layout(std140, set = 2, binding = 0) uniform UBO {
    mat4 inverse_vp_matrix;
};

// https://jcgt.org/published/0003/02/01/
vec2 signNotZero(vec2 v) {
    return vec2((v.x >= 0.0) ? +1.0 : -1.0, (v.y >= 0.0) ? +1.0 : -1.0);
}
vec2 encodeOctahedral(vec3 v) {
    vec2 p = v.xy * (1.0 / (abs(v.x) + abs(v.y) + abs(v.z)));
    return (v.z <= 0.0) ? ((1.0 - abs(p.yx)) * signNotZero(p)) : p;
}
vec3 decodeOctahedral(vec2 e) {
    vec3 v = vec3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0) v.xy = (1.0 - abs(v.yx)) * signNotZero(v.xy);
    return normalize(v);
}

void main() {
    ivec2 lowres_size = imageSize(u_lowres_indirect_light);
    ivec2 texcoords = ivec3(gl_GlobalInvocationID).xy;
    if (texcoords.x >= lowres_size.x || texcoords.y >= lowres_size.y) return;

    float depth = texture(u_lowres_depth, texcoords).r;
    vec3 normal = decodeOctahedral(texture(u_lowres_normal, texcoords).rg);

    vec4 ndc = vec4(
        2.0 * texcoords.x - 1.0,
        1.0 - 2.0 * texcoords.y,
        depth,
        1.0
    );
    vec4 world_pos = inverse_vp_matrix * ndc;
    world_pos /= world_pos.w;

    imageStore(u_lowres_indirect_light, texcoords, vec4(depth, texcoords, 1.0));
}
