#version 460

#define MIN_VOXEL_SIZE 0.244140625

layout(local_size_x = 16, local_size_y = 2, local_size_z = 2) in;

layout(set = 0, binding = 0) uniform sampler3D u_opacity_cascades;
layout(set = 0, binding = 1) uniform usampler3D u_diffuse_cascades;
layout(set = 0, binding = 2) uniform usampler3D u_emissive_cascades;

layout(rgba16f, set = 1, binding = 0) uniform image3D u_radiance_cache_cascades;

uint cascadeAt(vec3 pos) {
    vec3 a = abs(pos);
    float maximum = max(max(a.x, a.y), a.z);
    return uint(clamp(ceil(log2(maximum / (MIN_VOXEL_SIZE * 32))), 0, 8));
}

float voxelSize(uint cascade) {
    return MIN_VOXEL_SIZE * float(1 << cascade);
}

float dequantizeFromBitmask(uint bits, int nbits) {
    int q = bitCount(bits);
    return float(q) / float(nbits);
}

vec3 unpackDiffuse(uint packed) {
    uint r_pos_bits = (packed >> 27) & 0x1Fu;
    uint r_neg_bits = (packed >> 22) & 0x1Fu;
    uint g_pos_bits = (packed >> 16) & 0x3Fu;
    uint g_neg_bits = (packed >> 10) & 0x3Fu;
    uint b_pos_bits = (packed >>  5) & 0x1Fu;
    uint b_neg_bits =  packed        & 0x1Fu;

    float r_pos = dequantizeFromBitmask(r_pos_bits, 5);
    float r_neg = dequantizeFromBitmask(r_neg_bits, 5);
    float g_pos = dequantizeFromBitmask(g_pos_bits, 6);
    float g_neg = dequantizeFromBitmask(g_neg_bits, 6);
    float b_pos = dequantizeFromBitmask(b_pos_bits, 5);
    float b_neg = dequantizeFromBitmask(b_neg_bits, 5);

    float r = 0.5 + 0.5 * (r_pos - r_neg);
    float g = 0.5 + 0.5 * (g_pos - g_neg);
    float b = 0.5 + 0.5 * (b_pos - b_neg);

    return vec3(r, g, b);
}

const vec3 face_normals[6] = {
    vec3( 1,  0,  0),  
    vec3(-1,  0,  0),  
    vec3( 0,  1,  0),  
    vec3( 0, -1,  0),  
    vec3( 0,  0,  1),  
    vec3( 0,  0, -1),  
};

// vec3 unpackEmissiveEnergy(uint c) {
// }

// vec3 unpackEmissiveNormal(uint c) {
// }

void main() {

    // TODO dynamic
    vec3 light_dir = normalize(vec3(-1.0, 2.0, 0.5));
    float light_intensity = 0.5;
    
    ivec3 texcoords = ivec3(gl_GlobalInvocationID);
    if (texcoords.x >= 528 ||
        texcoords.y >= 66 ||
        texcoords.z >= 66) return;

    float opacity = texelFetch(u_opacity_cascades, texcoords + ivec3(0, 132, 0), 0).r;
    if (opacity == 0) return;

    vec3 diffuse = unpackDiffuse(texelFetch(u_diffuse_cascades, texcoords + ivec3(0, 132, 0), 0).r);

    for (int i = 0; i < 6; ++i) {

        vec3 rad = diffuse.rgb * 
            light_intensity *
            max(dot(face_normals[i], light_dir), 0.0);
        
        imageStore(
            u_radiance_cache_cascades,
            texcoords + ivec3(0, 66 * i, 0),
            vec4(rad, opacity)
        );
    }
}
