#version 460

#include "include/defines.glsl"

struct Bin {
    vec3 normal;
    float light_intensity;
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer BinCounters {
    uint bin_counters[];
};
layout(std430, set = 0, binding = 1) readonly buffer BinOffsets {
    uint bin_offsets[];
};
layout(std430, set = 0, binding = 2) readonly buffer Bins {
    Bin bins[];
};
layout(std430, set = 0, binding = 3) readonly buffer OpacityCascades {
    float opacity_cascades[];
};
layout(std430, set = 0, binding = 4) readonly buffer DiffuseCascades {
    uint diffuse_cascades[];
};

layout(rgba16f, set = 1, binding = 0) uniform image3D u_energy_targets;
layout(rgba8, set = 1, binding = 1) uniform image3D u_color_targets;

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

#include "include/voxel_utils.glsl"

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    if (global_id >= n_cascades * cascade_size[3]) return;

    uint cascade = indexToCascade(global_id);
    ivec3 pos = indexToPos(global_id);
    float voxel_size = voxelSize(cascade);
    float opacity = opacity_cascades[global_id];
    vec3 diffuse = unpackUnorm4x8(diffuse_cascades[global_id]).rgb;

    vec4 energy = vec4(0.0, 0.0, 0.0, 0.0);
    vec4 color = vec4(diffuse, opacity);

    uint count = bin_counters[global_id];
    uint offset = bin_offsets[global_id];
    for (int i = 0; i < count && i < 8; ++i) {
        Bin bin = bins[i + offset];
        // NOTE the normalization here actually needs to depend on the shadomap resolution/extent
        energy += vec4(0.0, 0.0, 0.0, bin.light_intensity / pow(10 * voxel_size, 2.0));
    }
    // one means of dealing with overinjected voxels is to just normalize like so
    // another could be to mipmap the shadowmap and to not inject as much into high cascades
    // or to only inject into the finest cascade per texel and then mipmap
    if (count > 8) energy *= float(count) / 8.0;
    
    imageStore(
        u_energy_targets,
        pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
        energy
    );
    imageStore(
        u_color_targets,
        pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
        color
    );
}
