#version 460

#define MIN_VOXEL_SIZE 0.244140625

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_src_hdr;
layout(set = 0, binding = 1) uniform sampler2D u_src_depth;
layout(set = 0, binding = 2) uniform sampler2D u_src_normal;

layout(r32ui, set = 1, binding = 0) uniform uimage3D u_radiance_targets;

layout(std140, set = 2, binding = 0) uniform UBO {
    mat4 inverse_vp_matrix;
};

uint cascadeAt(vec3 pos) {
    vec3 a = abs(pos);
    float maximum = max(max(a.x, a.y), a.z);
    return uint(clamp(ceil(log2(maximum / (MIN_VOXEL_SIZE * 32))), 0, 8));
}

float voxelSize(uint cascade) {
    return MIN_VOXEL_SIZE * float(1 << cascade);
}

// https://jcgt.org/published/0003/02/01/
vec2 signNotZero(vec2 v) {
    return vec2((v.x >= 0.0) ? +1.0 : -1.0, (v.y >= 0.0) ? +1.0 : -1.0);
}
vec2 encodeOctahedral(vec3 v) {
    vec2 p = v.xy * (1.0 / (abs(v.x) + abs(v.y) + abs(v.z)));
    return (v.z <= 0.0) ? ((1.0 - abs(p.yx)) * signNotZero(p)) : p;
}
vec3 decodeOctahedral(vec2 e) {
    vec3 v = vec3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0) v.xy = (1.0 - abs(v.yx)) * signNotZero(v.xy);
    return normalize(v);
}

void main() {
    vec2 texcoords =
        vec2(gl_GlobalInvocationID.xy) / (vec2(gl_WorkGroupSize * gl_NumWorkGroups) - 1);

    vec3 hdr = texture(u_src_hdr, texcoords).rgb;
    float depth = 1.0 - texture(u_src_depth, texcoords).r;
    vec3 normal = decodeOctahedral(texture(u_src_normal, texcoords).rg);

    uvec3 faces = uvec3(
        (normal.x < 0) ? 1 : 0,  
        (normal.y < 0) ? 3 : 2,  
        (normal.z < 0) ? 5 : 4  
    );
    vec3 weights = abs(normal);

    vec4 ndc = vec4(
        2.0 * texcoords.xy - 1.0,
        depth,
        1.0
    );
    vec4 world_pos = inverse_vp_matrix * ndc;
    world_pos /= world_pos.w;

    uint cascade = cascadeAt(world_pos.xyz);
    float voxel_size = voxelSize(cascade);
    ivec3 raw_voxel_pos = ivec3(world_pos / voxel_size) + ivec3(33, 33, 33);

    if (raw_voxel_pos.x < -33 || raw_voxel_pos.x > 32 ||
        raw_voxel_pos.y < -33 || raw_voxel_pos.y > 32 ||
        raw_voxel_pos.z < -33 || raw_voxel_pos.z > 32) return;

    uint current_packed;
    uint new_packed;
    uint original_packed;

    for (int i = 0; i < 3; ++i) {

        ivec3 voxel_pos_0 = raw_voxel_pos + ivec3(cascade * 66, faces[i] * 66, 0);
        ivec3 voxel_pos_1 = raw_voxel_pos + ivec3(cascade * 66, faces[i] * 66, 66);

        do {
            current_packed = imageLoad(u_radiance_targets, voxel_pos_0).r;
            new_packed = packHalf2x16(
                unpackHalf2x16(current_packed) + vec2(1.0, hdr.r) * weights[i]
            );
            original_packed = imageAtomicCompSwap(
                u_radiance_targets,
                voxel_pos_0,
                current_packed,
                new_packed
            );
        } while (original_packed != current_packed);

        do {
            current_packed = imageLoad(u_radiance_targets, voxel_pos_1).r;
            new_packed = packHalf2x16(
                unpackHalf2x16(current_packed) + hdr.bg * weights[i]
            );
            original_packed = imageAtomicCompSwap(
                u_radiance_targets,
                voxel_pos_1,
                current_packed,
                new_packed
            );
        } while (original_packed != current_packed);
        
    }

}
