#version 460

#include "include/defines.glsl"

struct Light {
    vec3 normal;  
    vec3 intensity;
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer BinCounters {
    uint bin_counters[];
};
layout(std430, set = 0, binding = 1) readonly buffer BinOffsets {
    uint bin_offsets[];
};
layout(std430, set = 0, binding = 2) readonly buffer Bins {
    Light bins[];
};
layout(std430, set = 0, binding = 3) readonly buffer VoxelCascades {
    uint voxel_cascades[];
};

layout(rgba16f, set = 1, binding = 0) uniform image3D u_energy_targets;
layout(rgba8, set = 1, binding = 1) uniform image3D u_color_targets;

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

#include "include/voxel_utils.glsl"

const float PI = 3.141592653589793;
const float sqrt_3_over_4pi = sqrt(3.0/(4.0 * PI));
const float inv_sqrt_4pi = 1.0 / sqrt(4.0 * PI);

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    if (global_id >= n_cascades * cascade_size[3]) return;

    uint cascade = indexToCascade(global_id);
    ivec3 pos = indexToPos(global_id);
    float voxel_size = voxelSize(cascade);
    vec4 color = unpackUnorm4x8(voxel_cascades[global_id]);

    vec4 energy = vec4(0.0, 0.0, 0.0, 0.0);

    uint count = bin_counters[global_id];
    uint offset = bin_offsets[global_id];
    // for (int i = 0; i < count && i < 8; ++i) {
    for (int i = 0; i < count; ++i) {
        Light bin = bins[i + offset];
        // NOTE the normalization here actually needs to depend on the shadomap resolution/extent
        // energy += vec4(0.0, 0.0, 0.0, bin.light_intensity / pow(10 * voxel_size, 2.0));
        float it = 0.33 * (bin.intensity.x + bin.intensity.y + bin.intensity.z);
        float intensity = it / pow(6.0 * voxel_size, 2.0);
        energy += intensity * vec4(sqrt_3_over_4pi * bin.normal, inv_sqrt_4pi);
    }
    // one means of dealing with overinjected voxels is to just normalize like so
    // another could be to mipmap the shadowmap and to not inject as much into high cascades
    // or to only inject into the finest cascade per texel and then mipmap
    // if (count > 8) energy *= float(count) / 8.0;
    
    imageStore(
        u_energy_targets,
        pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
        energy
    );
    imageStore(
        u_color_targets,
        pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
        color
    );

    // DEBUG
    if (count > 0) {
        imageStore(
            u_energy_targets,
            pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
            vec4(0.0, 0.0, 0.0, 1.0)
        );
        imageStore(
            u_color_targets,
            pos + ivec3(cascade_size.xyz / 2) + ivec3(cascade * cascade_size[0], 0, 0),
            vec4(1.0, 1.0, 1.0, 1.0)
        );
    }
}
