#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer VoxelCascades {
    uint voxel_cascades[];
};

layout(std430, set = 1, binding = 0) buffer SkylightVisibility {
    float skylight_visibility[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform InjectUBO {
    ivec4 bresenham[64];
    ivec4 origin;
    ivec4 step_a;
    ivec4 step_b;
    vec4 light_direction;
    vec4 light_intensity;
    uint n_a;
    uint n_b;
    uint mode;
    uint target_cascade;
};

#include "include/voxel_utils.glsl"

const float PI = 3.141592653589793;
const float sqrt_3_over_4pi = sqrt(3.0/(4.0 * PI));
const float inv_sqrt_4pi = 1.0 / sqrt(4.0 * PI);

void main() {
    uint global_id = gl_GlobalInvocationID.x;

    if (mode == 0u) {
        // sweep through cascade setting visibility
        int a = int(global_id % n_a);
        int b = int(global_id / n_a);
        ivec3 root = (origin + a * step_a + b * step_b).xyz;
        float opacity = 0.0;
        bool first_entry = true;
        for (uint i = 0u; i < 64; ++i) {
            ivec3 voxel_pos = root + bresenham[i].xyz;

            if (any(lessThan(voxel_pos, ivec3(-32))) ||
                any(greaterThan(voxel_pos, ivec3(31)))) continue;
            if (first_entry) {
                if (target_cascade == n_cascades - 1) {
                    // TODO think about the precise indexing
                    ivec3 outer_voxel_pos = voxel_pos / 2;
                    uint ix_outer_voxel = indexFromCascadePos(target_cascade + 1, outer_voxel_pos);
                    opacity = skylight_visibility[ix_outer_voxel];
                }
                first_entry = false;
            }
            
            uint ix_voxel = indexFromCascadePos(target_cascade, voxel_pos);
            // NOTE is correct blending or a harsher cutoff like this preferable?
            if (opacity < 1.0) {
                opacity = min(1.0, opacity + unpackUnorm4x8(voxel_cascades[ix_voxel]).a);
            }
            skylight_visibility[ix_voxel] = opacity;
        }
        return;
    }

    if (mode == 1u) {
        // compute energy and color
        return;
    }
}
