#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(set = 0, binding = 0) uniform sampler3D cascades_coverage;
layout(set = 0, binding = 1) uniform sampler3D cascades_diffuse;
layout(set = 0, binding = 2) uniform sampler3D cascades_emissive;
layout(set = 0, binding = 3) uniform sampler3D cascades_normal;

layout(rgba16f, set = 1, binding = 0) uniform image3D cascades_radiance;

layout(std140, set = 2, binding = 0) uniform LightingData {
    uint ix_temporal;
} lighting_data;

bool inBounds(vec3 position) {
    vec3 a = abs(position);
    float b = max(a.x, max(a.y, a.z));
    return b <= 504.0; // voxel size at cascade 8 is 16, farthest away voxel center is at 63 / 2
}

float sampleCoverageAt(vec3 position, float diameter) {
    uint cascade = uint(clamp(log2(diameter / 0.125), 0, 7) + 0.5);
    float cascade_size = 64.0 * 0.125 * float(1 << cascade);

    vec3 voxel_pos = position / cascade_size + 0.5;
    vec3 cascade_pos = vec3(
        0.125 * (voxel_pos.x + float(cascade)),
        0.5 * voxel_pos.y,
        voxel_pos.z
    );
    vec3 cascade_texel_half = 0.5 / vec3(512.0, 128.0, 64.0);
    vec3 cascade_min = vec3(
        0.125 * float(cascade),
        0.0,
        0.0
    );
    vec3 cascade_max = vec3(
        0.125 * (1.0 + float(cascade)),
        0.5,
        1.0
    );
    vec3 safe_pos = clamp(
        cascade_pos,
        cascade_min + cascade_texel_half,
        cascade_max - cascade_texel_half
    );
    return texture(cascades_coverage, safe_pos).r;
}

float shadowRayDir(vec3 origin, vec3 light_dir, float voxel_size) {
    // this function kinda works but
    // with cascaded vct, the the initial step actually needs to be handled with extra care
    // and we might need to always blend two mip levels while sampling the cascade
    // (assuming we want to get a perfectly smooth result)
    // this is because on the edge of a cascade, the first voxel sampled with suddenly changed
    // creating a visible discontinuity
    // 
    // to fix this we need smoothly blend the original step size
    // such that when a cascade ends we're already at the next cascades size as the initial step
    // and we need to do tetralinear interpolation between cascades
    // such that there is no sudden transition in resolution for the initial step
    //
    // however, it's probably fine to do this approximate version here for speed
    // and then rely on the precise cone tracing only in actual draw-pass lighting
    // since the voxel radiance will be smoothened by that anyway
     
    float scale_factor = 0.2; // diameter of cone at distance 1, TODO set based on hardness

    float acc = 0.0;
    origin += 1.8 * light_dir * voxel_size;
    float radius = scale_factor * 1.8 * voxel_size;

    while (acc < 0.95 && inBounds(origin)) {
        float cov = sampleCoverageAt(origin, 2 * radius);
        acc += (1 - acc) * cov;
    
        float distance = radius * (2 + scale_factor);
        radius = distance - radius;
        origin += light_dir * distance;
    }

    return (acc < 0.95) ? acc : 1.0;
}

void main() {
    ivec3 voxel_pos = ivec3(gl_GlobalInvocationID);
    uint cascade = uint(voxel_pos.x) / 64;
    float voxel_size = 0.125 * float(1 << cascade);
    vec3 voxel_world_center = voxel_size * (vec3(voxel_pos) - vec3(64 * cascade, 0, 0) - 32);
    
    float coverage = texelFetch(cascades_coverage, voxel_pos, 0).r;
    if (coverage < 0.05) {
        imageStore(cascades_radiance, voxel_pos, vec4(0.0, 0.0, 0.0, 0.0));
        return;   
    }
    
    vec3 diffuse = texelFetch(cascades_diffuse, voxel_pos, 0).rgb;
    vec3 emissive = texelFetch(cascades_emissive, voxel_pos, 0).rgb;
    vec3 normal = texelFetch(cascades_normal, voxel_pos, 0).rgb;

    vec3 light_dir = normalize(vec3(1.0, 2.0, 0.5));
    float light_intensity = 2.0;

    vec3 rad =
        diffuse *
        light_intensity *
        max(dot(normal, light_dir), 0.0) *
        (1.0 - shadowRayDir(voxel_world_center, light_dir, voxel_size));
    rad += emissive;

    imageStore(cascades_radiance, voxel_pos, vec4(rad, coverage));
}
