#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(rgba16f, set = 1, binding = 0) uniform image3D u_mipmapped_energy_cascades;
layout(rgba16f, set = 1, binding = 0) uniform image3D u_energy_cascades;
layout(rgba16f, set = 1, binding = 0) uniform image3D u_color_cascades; // for opacity weighting

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};
layout(std140, set = 2, binding = 1) uniform VoxelizeUBO {
    uint bin_group_offset; // we just need the target_cascade, but i didn't want to do the cpuside
    uint target_cascade;  
};

#include "include/voxel_utils.glsl"

ivec3 offsets[8] = {
    ivec3(0, 0, 0),
    ivec3(0, 0, 1),
    ivec3(0, 1, 0),
    ivec3(0, 1, 1),
    ivec3(1, 0, 0),
    ivec3(1, 0, 1),
    ivec3(1, 1, 0),
    ivec3(1, 1, 1)
};

void main() {
    // uint global_id = gl_GlobalInvocationID.x;
    // if (global_id >= cascade_size[3] / 8) return;

    // // hardcoded sizes for simplicity
    // ivec3 local_pos = ivec3(
    //      global_id & 0x1Fu,
    //     (global_id / 32) & 0x1Fu,
    //     (global_id / (32 * 32)) & 0x1Fu
    // ) - ivec3(16);

    // vec4 visibility = vec4(0.0);
    // for (uint i = 0; i < 8; ++i) {
    //     ivec3 pos = 2 * local_pos + offsets[i];
    //     visibility += unpackUnorm4x8(
    //         visibility_targets[indexFromCascadePos(target_cascade - 1, pos)]
    //     );
    // }
    // visibility *= 0.125;
    // visibility_targets[indexFromCascadePos(target_cascade, local_pos)] = packUnorm4x8(visibility);
}
