#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer VoxelTargets {
    uint voxel_targets[];
};
layout(std430, set = 0, binding = 1) readonly buffer NewVisTargets {
    uint visibility_targets[];
};

layout(std430, set = 1, binding = 0) buffer MipmapTargets {
    uint mipmap_targets[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // xyz
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};
layout(std140, set = 2, binding = 1) uniform MipmapUBO {
    ivec4 offset_a;
    ivec4 offset_b;
    uint target_cascade;  
};

#include "include/voxel_utils.glsl"

ivec3 offsets[8] = {
    ivec3(0, 0, 0),
    ivec3(0, 0, 1),
    ivec3(0, 1, 0),
    ivec3(0, 1, 1),
    ivec3(1, 0, 0),
    ivec3(1, 0, 1),
    ivec3(1, 1, 0),
    ivec3(1, 1, 1)
};

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    if (global_id >= cascade_size[3]) return;

    ivec3 local_pos = indexToPos(global_id);

    if (target_cascade == 0) {
        vec4 visibility = unpackUnorm4x8(visibility_targets[global_id]);
        ivec3 pos;
        pos = local_pos + offset_a.xyz;
        if (pos.x >= -32 && pos.x < 32 &&
            pos.y >= -32 && pos.y < 32 &&
            pos.z >= -32 && pos.z < 32) {
            visibility = max(
                visibility,
                unpackUnorm4x8(visibility_targets[indexFromCascadePos(0, pos)])
            );
        }
        pos = local_pos + offset_b.xyz;
        if (pos.x >= -32 && pos.x < 32 &&
            pos.y >= -32 && pos.y < 32 &&
            pos.z >= -32 && pos.z < 32) {
            visibility = max(
                visibility,
                unpackUnorm4x8(visibility_targets[indexFromCascadePos(0, pos)])
            );
        }
        mipmap_targets[global_id] = packUnorm4x8(visibility);
        return;
    }

    // hardcoded dims...
    if (local_pos.x < -16 || local_pos.x >= 15 ||
        local_pos.y < -16 || local_pos.y >= 15 ||
        local_pos.z < -16 || local_pos.z >= 15) {

        uint ix = indexFromCascadePos(target_cascade, local_pos);
        vec4 visibility = unpackUnorm4x8(visibility_targets[ix]);
        ivec3 pos;
        pos = local_pos + offset_a.xyz;
        if (pos.x >= -32 && pos.x < 32 &&
            pos.y >= -32 && pos.y < 32 &&
            pos.z >= -32 && pos.z < 32) {
            visibility = max(
                visibility,
                unpackUnorm4x8(visibility_targets[indexFromCascadePos(target_cascade, pos)])
            );
        }
        pos = local_pos + offset_b.xyz;
        if (pos.x >= -32 && pos.x < 32 &&
            pos.y >= -32 && pos.y < 32 &&
            pos.z >= -32 && pos.z < 32) {
            visibility = max(
                visibility,
                unpackUnorm4x8(visibility_targets[indexFromCascadePos(target_cascade, pos)])
            );
        }
        mipmap_targets[ix] = packUnorm4x8(visibility);

    } else {
        float opacity = 0.0;
        vec4 visibility = vec4(0.0);
        for (uint i = 0; i < 8; ++i) {
            ivec3 pos = 2 * local_pos + offsets[i];
            uint ix = indexFromCascadePos(target_cascade - 1, pos);
            opacity += unpackOpacity(voxel_targets[ix]);
            visibility += unpackUnorm4x8(visibility_targets[ix]);
        }
        if (opacity > 0) {
            visibility /= opacity;
        } else {
            visibility = vec4(0.0);
        }
        mipmap_targets[indexFromCascadePos(target_cascade, local_pos)] = packUnorm4x8(visibility);
    }
}
