#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(rgba16, set = 1, binding = 0) uniform image3D u_radiance_cache_cascades;

layout(std140, set = 2, binding = 0) uniform UBO {
    uint cascade;
};

void main() {
    ivec3 voxel_pos = ivec3(gl_GlobalInvocationID) - 16;
    ivec3 src_base = 2 * voxel_pos + ivec3(33 + 66 * (cascade - 1), 33, 33);
    ivec3 dst_base = voxel_pos + ivec3(33 + 66 * cascade, 33, 33);

    vec4 acc = vec4(0.0, 0.0, 0.0, 0.0);
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(0, 0, 0));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(0, 0, 1));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(0, 1, 0));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(0, 1, 1));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(1, 0, 0));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(1, 0, 1));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(1, 1, 0));
    acc += imageLoad(u_radiance_cache_cascades, src_base + ivec3(1, 1, 1));
    imageStore(u_radiance_cache_cascades, dst_base, 0.125 * acc);
}
