#version 460

#define WORKGROUP_SIZE 256
#define BLOCK_SIZE 32

struct KV {
    uint key;
    uint value;
};

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer KVsIn {
    uint n_kvs_in;
    KV kvs_in[];
};

layout(std430, set = 1, binding = 0) buffer HistogramBuffer {
    uint histograms[];
};

layout(std430, set = 1, binding = 1) buffer KVsOut {
    uint n_kvs_out;
    KV kvs_out[];
};

layout(std140, set = 2, binding = 0) uniform UBO {
    uint bit_shift;
};

shared uint local_offsets[256];

struct Flags {
    uint flags[WORKGROUP_SIZE / 32];
};
shared Flags[256] flags;

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint local_id = gl_LocalInvocationID.x;
    uint workgroup_id = gl_WorkGroupID.x;
    uint n_workgroups = gl_NumWorkGroups.x;

    if (global_id == 0) {
        n_kvs_out = n_kvs_in;
    }
    if (local_id < 256) {
        uint offset = 0;
        for (int i = 0; i < workgroup_id; ++i) {
            offset += histograms[256 * i + local_id];
        }
        // now holds the offset for this radix for this workgroup in kvs_out
        local_offsets[local_id] = offset + histograms[local_id + 256 * n_workgroups];
    }
    barrier();

    // stable scatter pass based entirely on https://github.com/MircoWerner/VkRadixSort/
    // the idea is, within a block, we mark the number of kvs with each radix
    // and then, we can reference that for each one to figure out what slot it goes into
    const uint flags_bin = local_id / 32;
    const uint flags_bit = 1 << (local_id % 32);

    for (int i = 0; i < BLOCK_SIZE; ++i) {
        uint ix = WORKGROUP_SIZE * i + WORKGROUP_SIZE * BLOCK_SIZE * workgroup_id + local_id;

        if (local_id < 256) {
            for (int j = 0; j < WORKGROUP_SIZE/ 32; ++j) {
                flags[local_id].flags[j] = 0;
            }
        }
        barrier();
        
        // set a flag saying this worker wants to put an item into this radix
        KV kv;
        uint radix;
        uint offset;
        if (ix < n_kvs_in) {
            kv = kvs_in[ix];
            radix = (kv.key >> bit_shift) & 0xFFu;
            offset = local_offsets[radix];
            atomicOr(flags[radix].flags[flags_bin], flags_bit);
        }
        barrier();

        if (ix < n_kvs_in) {
            uint prefix = 0;
            uint count = 0;
            for (uint j = 0; j < WORKGROUP_SIZE / 32; ++j) {
                // count the nuber of set flags for this radix before this worker
                // that's the offset for this element
                // that way, we preserve the order from kvs_in
                const uint bits = flags[radix].flags[j];
                const uint full_count = bitCount(bits);
                const uint partial_count = bitCount(bits & (flags_bit - 1));
                prefix += (j < flags_bin) ? full_count : 0;
                prefix += (j == flags_bin) ? partial_count : 0;
                count += full_count;
            }
            kvs_out[offset + prefix] = kv;
            // finally, we need to update the offsets to account for what we inserted
            if (prefix == count - 1) {
                atomicAdd(local_offsets[radix], count);
            }
        }
        barrier();
    }
}
