#version 460

#define WORKGROUP_SIZE 256
#define BLOCK_SIZE 32

struct IndirectDispatchCommand {
    uint groupcount_x;
    uint groupcount_y;
    uint groupcount_z;
};

struct KV {
    uint key;
    uint value;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer KVs {
    uint n_kvs;
    KV kvs[];
};

layout(std430, set = 1, binding = 0) buffer IndirectDispatchCommands {
    IndirectDispatchCommand indirect_dispatch_commands[];
};

void main() {
    indirect_dispatch_commands[0] = IndirectDispatchCommand(
        (n_kvs + WORKGROUP_SIZE * BLOCK_SIZE - 1) / (WORKGROUP_SIZE * BLOCK_SIZE), 1, 1
    );
}
