#version 460

#define WORKGROUP_SIZE 256
#define BLOCK_SIZE 32

struct KV {
    uint key;
    uint value;
};

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer KVs {
    uint n_kvs;
    KV kvs[];
};

layout(std430, set = 1, binding = 0) buffer HistogramBuffer {
    uint histograms[];
};

layout(std140, set = 2, binding = 0) uniform UBO {
    uint bit_shift;
};

shared uint local_hist[256];

void main() {
    uint local_id = gl_LocalInvocationID.x;
    uint workgroup_id = gl_WorkGroupID.x;

    if (local_id < 256) {
        local_hist[local_id] = 0;
    }
    barrier();

    for (int i = 0; i < BLOCK_SIZE; ++i) {
        uint ix = WORKGROUP_SIZE * i + WORKGROUP_SIZE * BLOCK_SIZE * workgroup_id + local_id;
        if (ix < n_kvs) {
            uint key = kvs[ix].key;
            uint radix = (key >> bit_shift) & 0xFFu;
            atomicAdd(local_hist[radix], 1);
        }
    }
    barrier();

    if (local_id < 256) {
        histograms[local_id + 256 * workgroup_id] = local_hist[local_id];
    }
}

// This shader is derived from VkRadixSort by Mirco Werner.
// The original source code is available at: https://github.com/MircoWerner/VkRadixSort/
// The original code is licensed under the MIT License:

// MIT License

// Copyright (c) 2023 Mirco Werner

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
