#version 460

#define WORKGROUP_SIZE 256

struct KV {
    uint key;
    uint value;
};

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer KVs {
    uint n_kvs;
    KV kvs[];
};

layout(std430, set = 1, binding = 0) buffer HistogramBuffer {
    uint histograms[];
};

shared uint local_hist[256];

void main() {
    uint local_id = gl_LocalInvocationID.x;
    // NOTE n_workgroups in the histogram and scatter pass
    uint n_workgroups = (n_kvs + WORKGROUP_SIZE * 32 - 1) / (WORKGROUP_SIZE * 32);

    uint bin_total = 0;
    for (uint i = 0; i < n_workgroups; ++i) {
        bin_total += histograms[i * 256 + local_id];
    }
    
    local_hist[local_id] = bin_total;
    barrier();

    for (uint i = 1; i < 256; i *= 2) {
        uint j = (local_id + 1) * i * 2 - 1;
        if (j < 256) local_hist[j] += local_hist[j - i];
        barrier();
    }

    if (local_id == 0) {
        local_hist[255] = 0;
    }
    barrier();

    for (uint i = 128 / 2; i > 0; i /= 2) {
        uint j = (local_id + 1) * i * 2 - 1;
        if (j < 256) {
            uint tmp = local_hist[j - i];
            local_hist[j - i] = local_hist[j];
            local_hist[j] += tmp;
        }
        barrier();
    }

    if (local_id < 256) {
        histograms[local_id + 256 * n_workgroups] = local_hist[local_id];
        histograms[local_id + 256 * n_workgroups + 256] = local_hist[local_id];
    }
    
    
}

