#version 460

#define WORKGROUP_SIZE 256
#define BLOCK_SIZE 32

struct KV {
    uint key;
    uint value;
};

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer KVsIn {
    uint n_kvs_in;
    KV kvs_in[];
};

layout(std430, set = 1, binding = 0) buffer HistogramBuffer {
    uint histograms[];
};

layout(std430, set = 1, binding = 1) buffer KVsOut {
    uint n_kvs_out;
    KV kvs_out[];
};

layout(std140, set = 2, binding = 0) uniform UBO {
    uint bit_shift;
};

shared uint local_hist[256];
shared uint local_offsets[256];
shared uint local_counters[256];

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint local_id = gl_LocalInvocationID.x;
    uint workgroup_id = gl_WorkGroupID.x;
    uint n_workgroups = gl_NumWorkGroups.x;

    if (global_id == 0) {
        n_kvs_out = n_kvs_in;
    }
    if (local_id < 256) {
        local_hist[local_id] = histograms[local_id + 256 * workgroup_id];
        local_offsets[local_id] = 0;
        local_counters[local_id] = 0;
    }
    barrier();

    if (local_id < 256) {
        if (local_hist[local_id] > 0) {
            local_offsets[local_id] = atomicAdd(
                histograms[local_id + 256 * n_workgroups + 256],
                local_hist[local_id]
            );
        }
    }
    barrier();

    for (int i = 0; i < BLOCK_SIZE; ++i) {
        uint ix = WORKGROUP_SIZE * i + WORKGROUP_SIZE * BLOCK_SIZE * workgroup_id + local_id;
        if (ix < n_kvs_in) {
            KV kv = kvs_in[ix];
            uint radix = (kv.key >> bit_shift) & 0xFFu;
            kvs_out[local_offsets[radix] + atomicAdd(local_counters[radix], 1)] = kv;
        }
    }
}
