#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Vertex {
    vec3 position;
    vec3 normal;  
};

struct Triangle {
    // TODO pack to minimize memory usage
    vec3 p0;
    vec3 p1;
    vec3 p2;
    vec3 diffuse;
    float emissive_power;
};

layout(std430, set = 0, binding = 0) readonly buffer VertexBuffer {
    Vertex vertices[];
};
layout(std430, set = 0, binding = 1) readonly buffer IndexBuffer {
    uint indices[];
};

layout(std430, set = 1, binding = 0) buffer BinCounters {
    uint bin_counters[];
};
layout(std430, set = 1, binding = 1) buffer BinOffsets {
    uint bin_offsets[];
};
layout(std430, set = 1, binding = 2) buffer Bins {
    Triangle bins[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // x, y, z, x*y*z
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform BinningUBO {
    mat4 model_matrix;
    vec4 diffuse; // rgb 0-1
    vec4 emissive; // rgb 0-inf
    uint target_cascade;
    uint n_triangles;
    uint first_index;
    uint first_vertex;
    uint binning_mode;
};

#include "include/voxel_utils.glsl"

void main() {
    uint ix_src_triangle = gl_GlobalInvocationID.x;
    if (ix_src_triangle >= n_triangles) return;
    
    uint index_offset = first_index + 3 * ix_src_triangle;
    uint i0 = indices[index_offset + 0] + first_vertex;
    uint i1 = indices[index_offset + 1] + first_vertex;
    uint i2 = indices[index_offset + 2] + first_vertex;

    vec3 p0_model = vertices[i0].position;
    vec3 p1_model = vertices[i1].position;
    vec3 p2_model = vertices[i2].position;

    vec3 p0 = (model_matrix * vec4(p0_model, 1.0)).xyz - anchors[target_cascade].xyz;
    vec3 p1 = (model_matrix * vec4(p1_model, 1.0)).xyz - anchors[target_cascade].xyz;
    vec3 p2 = (model_matrix * vec4(p2_model, 1.0)).xyz - anchors[target_cascade].xyz;

    // each bins has 4x4x4 voxels
    float bin_size = voxelSize(target_cascade) * 4;
    ivec3 cascade_size_half = ivec3(cascade_size / 8);

    vec3 lower_bound = min(min(p0, p1), p2);
    vec3 upper_bound = max(max(p0, p1), p2);
    ivec3 bin_lower_bound = max(ivec3(floor(lower_bound / bin_size)), -cascade_size_half);
    ivec3 bin_upper_bound = min(ivec3(floor(upper_bound / bin_size)), cascade_size_half - 1);
    for (int x = bin_lower_bound.x; x <= bin_upper_bound.x; ++x) {
        for (int y = bin_lower_bound.y; y <= bin_upper_bound.y; ++y) {
            for (int z = bin_lower_bound.z; z <= bin_upper_bound.z; ++z) {
                ivec3 bin_pos = ivec3(x, y, z);
                uint bin_index = indexFromCascadePos(target_cascade, bin_pos); // FIXME FIXME
                atomicAdd(bin_counters[bin_index], 1);
                atomicAdd(bin_offsets[bin_index], 1);
            }
        }
    }
}
