#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Triangle {
    uint p0[2];
    uint p1[2];
    uint p2[2];
    uint diffuse;
    uint emissive;
};

layout(std430, set = 0, binding = 0) readonly buffer Buffer {
    uint n_buffered_triangles[2];
    Triangle buf[];
};

layout(std430, set = 1, binding = 0) buffer BinCounters {
    uint bin_counters[];
};
layout(std430, set = 1, binding = 1) buffer BinOffsets {
    uint bin_offsets[]; // could be readonly
};
layout(std430, set = 1, binding = 2) buffer Bins {
    Triangle bins[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // x, y, z, x*y*z
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};
layout(std140, set = 2, binding = 1) uniform BinningBUBO {
    uint target_cascade;
    uint bin_group_offset;
    uint buffer_group_index;
    uint buffer_group_offset;
};

#include "include/voxel_utils.glsl"

uint binIndex(ivec3 pos) {
    uvec3 upos = uvec3(pos + ivec3(cascade_size.xyz / 8));
    return upos.x +
           upos.y * cascade_size[0] / 4u +
           upos.z * cascade_size[0] / 4u * cascade_size[1] / 4u;
}

uint triangleVolume(ivec3 lower_bound, ivec3 upper_bound) {
    ivec3 extent = (upper_bound + 1) - lower_bound;
    return extent.x * extent.y * extent.z;
}

void main() {
    uint ix_src_triangle = gl_GlobalInvocationID.x;
    if (ix_src_triangle >= n_buffered_triangles[buffer_group_index]) return;

    Triangle tri = buf[ix_src_triangle + buffer_group_offset];
    vec3 p0 = vec3(
        unpackHalf2x16(tri.p0[0]),
        unpackHalf2x16(tri.p0[1]).x
    );
    vec3 p1 = vec3(
        unpackHalf2x16(tri.p1[0]),
        unpackHalf2x16(tri.p1[1]).x
    );
    vec3 p2 = vec3(
        unpackHalf2x16(tri.p2[0]),
        unpackHalf2x16(tri.p2[1]).x
    );

    vec3 lower_bound = min(min(p0, p1), p2);
    vec3 upper_bound = max(max(p0, p1), p2);
    
    // each bins has 4x4x4 voxels
    float bin_size = voxelSize(target_cascade) * 4;
    ivec3 bin_cascade_size_half = ivec3(cascade_size / 8u);

    // we could test for bin intersection here as well instead of binning to everythign in the bbox
    ivec3 bin_lower_bound = max(ivec3(floor(lower_bound / bin_size)), -bin_cascade_size_half);
    ivec3 bin_upper_bound = min(ivec3(floor(upper_bound / bin_size)), bin_cascade_size_half - 1);
    for (int x = bin_lower_bound.x; x <= bin_upper_bound.x; ++x) {
        for (int y = bin_lower_bound.y; y <= bin_upper_bound.y; ++y) {
            for (int z = bin_lower_bound.z; z <= bin_upper_bound.z; ++z) {
                ivec3 bin_pos = ivec3(x, y, z);
                uint bin_index = binIndex(bin_pos);
                uint offset = bin_offsets[bin_index + bin_group_offset];
                uint index = atomicAdd(bin_counters[bin_index + bin_group_offset], 1u);
                bins[offset + index] = tri;
            }
        }
    }
}   
