#version 460

#include "include/defines.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Vertex {
    vec3 position;
    vec3 normal;  
};

struct Triangle {
    // NOTE could pack even more aggresively
    // unclear if unpacking vs conputing the normal is worth it
    uint p0[2];
    uint p1[2];
    uint p2[2];
    uint diffuse;
    uint emissive;
};

layout(std430, set = 0, binding = 0) readonly buffer VertexBuffer {
    Vertex vertices[];
};
layout(std430, set = 0, binding = 1) readonly buffer IndexBuffer {
    uint indices[];
};

layout(std430, set = 1, binding = 0) buffer BinCounters {
    uint bin_counters[]; // not used
};
layout(std430, set = 1, binding = 1) buffer BinOffsets {
    uint bin_offsets[];
};
layout(std430, set = 1, binding = 2) buffer Buffer {
    uint n_buffered_triangles[2];
    Triangle buf[];
};
layout(std430, set = 1, binding = 3) buffer VoxelTargets {
    uint voxel_targets[];
};

layout(std140, set = 2, binding = 0) uniform CommonUBO {
    uvec4 cascade_size; // x, y, z, x*y*z
    uvec4 cascade_mask;
    uint n_cascades;
    float min_voxel_size;
    vec4 anchors[MAX_CASCADES];
};

layout(std140, set = 2, binding = 1) uniform BinningAUBO {
    mat4 model_matrix;
    vec4 diffuse; // rgb 0-1
    vec4 emissive; // rgb 0-inf
    uint target_cascade;
    uint bin_group_offset;
    uint buffer_group_index;
    uint buffer_group_offset;
    uint n_triangles;
    uint first_index;
    uint first_vertex;
};

#include "include/voxel_utils.glsl"

uint binIndex(ivec3 pos) {
    uvec3 upos = uvec3(pos + ivec3(cascade_size.xyz / 8));
    return upos.x +
           upos.y * cascade_size[0] / 4u +
           upos.z * cascade_size[0] / 4u * cascade_size[1] / 4u;
}

uint triangleVolume(ivec3 lower_bound, ivec3 upper_bound) {
    ivec3 extent = (upper_bound + 1) - lower_bound;
    return extent.x * extent.y * extent.z;
}

void main() {
    uint ix_src_triangle = gl_GlobalInvocationID.x;
    if (ix_src_triangle >= n_triangles) return;
    
    uint index_offset = first_index + 3 * ix_src_triangle;
    uint i0 = indices[index_offset + 0] + first_vertex;
    uint i1 = indices[index_offset + 1] + first_vertex;
    uint i2 = indices[index_offset + 2] + first_vertex;
    vec3 p0_model = vertices[i0].position;
    vec3 p1_model = vertices[i1].position;
    vec3 p2_model = vertices[i2].position;

    vec3 p0 = (model_matrix * vec4(p0_model, 1.0)).xyz - anchors[target_cascade].xyz;
    vec3 p1 = (model_matrix * vec4(p1_model, 1.0)).xyz - anchors[target_cascade].xyz;
    vec3 p2 = (model_matrix * vec4(p2_model, 1.0)).xyz - anchors[target_cascade].xyz;

    vec3 normal = normalize(cross(p1 - p0, p2 - p0));
    vec3 lower_bound = min(min(p0, p1), p2);
    vec3 upper_bound = max(max(p0, p1), p2);

    uint packed = packDiffuseNormalOpacity(diffuse.rgb, normal, 1.0);

    // directly voxelize small triangles
    // this is increases the cost of the binning if we have many small triangles
    // so should be combined with an LOD system to avoid voxelizing very fine geometry
    // but it is absolutely necessary to avoid overloading the voxelization pass
    // a further optimization might be to do voxelization with intersection testing here as well
    // for triangles that are bigger than 2 voxels, but smaller than some threshold
    float voxel_size = voxelSize(target_cascade);
    ivec3 cascade_size_half = ivec3(cascade_size / 2u);
    ivec3 voxel_lower_bound = max(ivec3(floor(lower_bound / voxel_size)), -cascade_size_half);
    ivec3 voxel_upper_bound = min(ivec3(floor(upper_bound / voxel_size)), cascade_size_half - 1);
    if (triangleVolume(voxel_lower_bound, voxel_upper_bound) <= 2) {
        for (int x = voxel_lower_bound.x; x <= voxel_upper_bound.x; ++x) {
            for (int y = voxel_lower_bound.y; y <= voxel_upper_bound.y; ++y) {
                for (int z = voxel_lower_bound.z; z <= voxel_upper_bound.z; ++z) {
                    ivec3 voxel_pos = ivec3(x, y, z);
                    uint voxel_index = indexFromCascadePos(target_cascade, voxel_pos);
                    packed = setPackedOpacity(packed, 0.5);
                    atomicOr(voxel_targets[voxel_index], packed);
                }
            }
        }
        return;
    }

    // count number of triangles per bin and store to sort into bins later
    float bin_size = voxelSize(target_cascade) * 4;
    ivec3 bin_cascade_size_half = ivec3(cascade_size / 8u);
    ivec3 bin_lower_bound = max(ivec3(floor(lower_bound / bin_size)), -bin_cascade_size_half);
    ivec3 bin_upper_bound = min(ivec3(floor(upper_bound / bin_size)), bin_cascade_size_half - 1);
    for (int x = bin_lower_bound.x; x <= bin_upper_bound.x; ++x) {
        for (int y = bin_lower_bound.y; y <= bin_upper_bound.y; ++y) {
            for (int z = bin_lower_bound.z; z <= bin_upper_bound.z; ++z) {
                ivec3 bin_pos = ivec3(x, y, z);
                uint bin_index = binIndex(bin_pos);
                atomicAdd(bin_offsets[bin_index + bin_group_offset], 1);
            }
        }
    }

    Triangle tri;
    tri.p0[0] = packHalf2x16(p0.xy);
    tri.p0[1] = packHalf2x16(vec2(p0.z, normal.x));
    tri.p1[0] = packHalf2x16(p1.xy);
    tri.p1[1] = packHalf2x16(vec2(p1.z, normal.x));
    tri.p2[0] = packHalf2x16(p2.xy);
    tri.p2[1] = packHalf2x16(vec2(p2.z, normal.x));
    tri.diffuse = packed;
    tri.emissive = 0; // we should actually do the voxel target packing here
    uint ix = atomicAdd(n_buffered_triangles[buffer_group_index], 1); // contention risk?
    buf[ix + buffer_group_offset] = tri;
}
