#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_lowres_depth;
layout(set = 0, binding = 1) uniform sampler2D u_lowres_normal;
layout(set = 0, binding = 2) uniform sampler2D u_lowres_indirect_light;
layout(set = 0, binding = 3) uniform sampler2D u_depth_target;
layout(set = 0, binding = 4) uniform sampler2D u_normal_target;

layout(rgba16f, set = 1, binding = 0) uniform image2D u_indirect_light;

// https://jcgt.org/published/0003/02/01/
vec2 signNotZero(vec2 v) {
    return vec2((v.x >= 0.0) ? +1.0 : -1.0, (v.y >= 0.0) ? +1.0 : -1.0);
}
vec2 encodeOctahedral(vec3 v) {
    vec2 p = v.xy * (1.0 / (abs(v.x) + abs(v.y) + abs(v.z)));
    return (v.z <= 0.0) ? ((1.0 - abs(p.yx)) * signNotZero(p)) : p;
}
vec3 decodeOctahedral(vec2 e) {
    vec3 v = vec3(e.xy, 1.0 - abs(e.x) - abs(e.y));
    if (v.z < 0) v.xy = (1.0 - abs(v.yx)) * signNotZero(v.xy);
    return normalize(v);
}

void main() {
    ivec2 size = imageSize(u_indirect_light);
    ivec2 texcoords = ivec3(gl_GlobalInvocationID).xy;
    if (texcoords.x >= size.x || texcoords.y >= size.y) return;
    
    // TODO upsample properly
    // vec4 rad = texelFetch(u_lowres_indirect_light, texcoords / 4, 0);
    // imageStore(u_indirect_light, texcoords, rad);

    float depth = texelFetch(u_depth_target, texcoords, 0).r;
    vec3 normal = decodeOctahedral(texelFetch(u_normal_target, texcoords, 0).rg);

    const float var = 2.0 * pow(2.0, 2.0);
    const float var_depth = 2.0 * pow(1.0, 2.0);
    const float var_normal = 2.0 * pow(0.2, 2.0);
    
    // this feels like so many texture reads?
    vec4 acc = vec4(0.0, 0.0, 0.0, 0.0);
    float total_weight = 0.0;
    for (int x = -2; x <= 2; ++x) {
        for (int y = -2; y <= 2; ++y) {
            ivec2 uv = clamp(texcoords / 4 + ivec2(x, y), ivec2(0, 0), size);
            vec4 lr_rad = texelFetch(u_lowres_indirect_light, uv, 0);
            float lr_depth = texelFetch(u_lowres_depth, uv, 0).r;
            vec3 lr_normal = decodeOctahedral(texelFetch(u_lowres_normal, uv, 0).rg);

            vec2 lowres_pos = (vec2(uv) + 0.5) * 4.0;
            vec2 highres_pos = vec2(texcoords) + 0.5;
            vec2 dxy = lowres_pos - highres_pos;
            float weight = exp(-dot(dxy, dxy) / var);
            float world_depth = 1.0 / (depth * (10 - 1e-5) + 1e-5);
            float world_lr_depth = 1.0 / (lr_depth * (10 - 1e-5) + 1e-5);
            float dd = world_depth - world_lr_depth;
            weight *= exp(-dd * dd / var_depth);
            weight *= exp(-max(0.0, 1.0 - dot(lr_normal, normal)) / var_normal);

            acc += lr_rad * weight;
            total_weight += weight;
        }
    }
    imageStore(u_indirect_light, texcoords, acc / total_weight);
}
