#version 460

struct Vertex {
    vec3 position;
    vec3 normal;  
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) readonly buffer VertexBuffer {
    Vertex vertices[];
} vertex_buffer;

layout(std430, set = 0, binding = 1) readonly buffer IndexBuffer {
    uint indices[];
} index_buffer;

layout(r32ui, set = 1, binding = 0) uniform uimage3D cascade;

layout(set = 2, binding = 0) uniform VoxelizeData {
    mat4 model_matrix;
    uint n_triangles;
} voxelize_data;

bool intersectVoxelTriangle(vec3 low, vec3 ext, vec3 p0, vec3 p1, vec3 p2) {
    // https://omnigoat.github.io/2015/03/09/box-triangle-intersection/
    vec3 n = normalize(cross(p1 - p0, p2 - p0));

    vec3 c = vec3(
        (n.x > 0.0) ? ext.x : 0.0,
        (n.y > 0.0) ? ext.y : 0.0,
        (n.z > 0.0) ? ext.z : 0.0
    );
    float d1 = dot(n, low + c - p0);
    float d2 = dot(n, low + ext - c - p0);
    if (d1 * d2 > 0.0) return false;

    vec3 e0 = p1 - p0;
    vec3 e1 = p2 - p1;
    vec3 e2 = p0 - p2;

    float xym = sign(n.z);

    vec2 ne0xy = vec2(-e0.y, e0.x) * xym;
    float de0xy = -dot(ne0xy, p0.xy) + max(0.0, ext.x * ne0xy.x) + max(0.0, ext.y * ne0xy.y);
    if (dot(ne0xy, low.xy) + de0xy < 0.0) return false;

    vec2 ne1xy = vec2(-e1.y, e1.x) * xym;
    float de1xy = -dot(ne1xy, p1.xy) + max(0.0, ext.x * ne1xy.x) + max(0.0, ext.y * ne1xy.y);
    if (dot(ne1xy, low.xy) + de1xy < 0.0) return false;

    vec2 ne2xy = vec2(-e2.y, e2.x) * xym;
    float de2xy = -dot(ne2xy, p2.xy) + max(0.0, ext.x * ne2xy.x) + max(0.0, ext.y * ne2xy.y);
    if (dot(ne2xy, low.xy) + de2xy < 0.0) return false;

    float yzm = sign(n.x);

    vec2 ne0yz = vec2(-e0.z, e0.y) * yzm;
    float de0yz = -dot(ne0yz, p0.yz) + max(0.0, ext.y * ne0yz.x) + max(0.0, ext.z * ne0yz.y);
    if (dot(ne0yz, low.yz) + de0yz < 0.0) return false;

    vec2 ne1yz = vec2(-e1.z, e1.y) * yzm;
    float de1yz = -dot(ne1yz, p1.yz) + max(0.0, ext.y * ne1yz.x) + max(0.0, ext.z * ne1yz.y);
    if (dot(ne1yz, low.yz) + de1yz < 0.0) return false;

    vec2 ne2yz = vec2(-e2.z, e2.y) * yzm;
    float de2yz = -dot(ne2yz, p2.yz) + max(0.0, ext.y * ne2yz.x) + max(0.0, ext.z * ne2yz.y);
    if (dot(ne2yz, low.yz) + de2yz < 0.0) return false;

    float zxm = sign(n.y);

    vec2 ne0zx = vec2(-e0.x, e0.z) * zxm;
    float de0zx = -dot(ne0zx, p0.zx) + max(0.0, ext.z * ne0zx.x) + max(0.0, ext.x * ne0zx.y);
    if (dot(ne0zx, low.zx) + de0zx < 0.0) return false;

    vec2 ne1zx = vec2(-e1.x, e1.z) * zxm;
    float de1zx = -dot(ne1zx, p1.zx) + max(0.0, ext.z * ne1zx.x) + max(0.0, ext.x * ne1zx.y);
    if (dot(ne1zx, low.zx) + de1zx < 0.0) return false;

    vec2 ne2zx = vec2(-e2.x, e2.z) * zxm;
    float de2zx = -dot(ne2zx, p2.zx) + max(0.0, ext.z * ne2zx.x) + max(0.0, ext.x * ne2zx.y);
    if (dot(ne2zx, low.zx) + de2zx < 0.0) return false;

    return true;
}

void main() {
    uint ix_triangle = gl_GlobalInvocationID.x;
    if (ix_triangle >= voxelize_data.n_triangles) return;

    uint first_index = 3 * ix_triangle;
    uint i0 = index_buffer.indices[first_index + 0];
    uint i1 = index_buffer.indices[first_index + 1];
    uint i2 = index_buffer.indices[first_index + 2];

    vec3 p0_model = vertex_buffer.vertices[i0].position;
    vec3 p1_model = vertex_buffer.vertices[i1].position;
    vec3 p2_model = vertex_buffer.vertices[i2].position;

    vec3 p0 = (voxelize_data.model_matrix * vec4(p0_model, 1.0)).xyz;
    vec3 p1 = (voxelize_data.model_matrix * vec4(p1_model, 1.0)).xyz;
    vec3 p2 = (voxelize_data.model_matrix * vec4(p2_model, 1.0)).xyz;
    
    // iterate over the triangle aabb and test for intersection with each voxel
    vec3 lower_bound = min(min(p0, p1), p2);
    vec3 upper_bound = max(max(p0, p1), p2);
    ivec3 voxel_lower_bound = ivec3(floor(lower_bound / 0.125));
    ivec3 voxel_upper_bound = ivec3(floor(upper_bound / 0.125));
    for (int x = voxel_lower_bound.x; x <= voxel_upper_bound.x; ++x) {
        if (x < -32 || x >= 32) continue;
        for (int y = voxel_lower_bound.y; y <= voxel_upper_bound.y; ++y) {
            if (y < -32 || y >= 32) continue;
            for (int z = voxel_lower_bound.z; z <= voxel_upper_bound.z; ++z) {
                if (z < -32 || z >= 32) continue;

                vec3 low = 0.125 * vec3(x, y, z);
                vec3 ext = vec3(0.125, 0.125, 0.125);
                if (!intersectVoxelTriangle(low, ext, p0, p1, p2)) {
                    continue;
                }

                uint color = 0xFFFFFFFFu;
                if (ix_triangle == 0 || ix_triangle == 1) color = 0xFF0000FFu;
                if (ix_triangle == 2 || ix_triangle == 3) color = 0x00FF00FFu;
                if (ix_triangle == 4 || ix_triangle == 5) color = 0x0000FFFFu;
                if (ix_triangle == 6 || ix_triangle == 7) color = 0xFFFF00FFu;
                if (ix_triangle == 8 || ix_triangle == 9) color = 0x00FFFFFFu;
                if (ix_triangle == 10 || ix_triangle == 11) color = 0xFF00FFFFu;
                
                uint current;
                uint new;
                uint original;
                do {
                    current = imageLoad(cascade, ivec3(x, y, z) + 32).r;
                    // new = 0xFFFFFFAAu;
                    new = color;
                    original = imageAtomicCompSwap(cascade, ivec3(x, y, z) + 32, current, new);
                } while (original != current);
            }
        }
    }
}
