#version 460

#define MIN_VOXEL_SIZE 0.109375

struct Vertex {
    vec3 position;
    vec3 normal;  
};

struct TriangleData {
    vec3 normal;
    vec4 diffuse;
    vec3 emissive;
    float roughness;
    float coverage;
};

struct TriangleIntersection {
    uint ix_voxel;
    uint ix_triangle;
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 1, binding = 0) buffer TriangleCounterBuffer {
    uint n_triangles;
} b_triangle_counters;

layout(std430, set = 1, binding = 1) buffer TriangleDataBuffer {
    TriangleData triangles[];
} b_triangle_data;

layout(std430, set = 1, binding = 2) buffer TriangleListBuffer {
    TriangleIntersection isects[];
} b_triangle_isects;

layout(std430, set = 0, binding = 0) readonly buffer VertexBuffer {
    Vertex vertices[];
} b_vertices;

layout(std430, set = 0, binding = 1) readonly buffer IndexBuffer {
    uint indices[];
} b_indices;

layout(std140, set = 2, binding = 0) uniform VoxelizeData {
    mat4 model_matrix;
    mat4 normal_matrix;
    vec4 diffuse;
    vec4 emissive;
    float roughness;
    uint n_triangles;
} voxelize_data;

float voxelSize(uint cascade) {
    return MIN_VOXEL_SIZE * float(1 << cascade);
}

bool intersectVoxelTriangle(vec3 low, vec3 ext, vec3 p0, vec3 p1, vec3 p2) {
    // https://omnigoat.github.io/2015/03/09/box-triangle-intersection/
    vec3 n = normalize(cross(p1 - p0, p2 - p0));

    vec3 c = vec3(
        (n.x > 0.0) ? ext.x : 0.0,
        (n.y > 0.0) ? ext.y : 0.0,
        (n.z > 0.0) ? ext.z : 0.0
    );
    float d1 = dot(n, low + c - p0);
    float d2 = dot(n, low + ext - c - p0);
    if (d1 * d2 > 0.0) return false;

    vec3 e0 = p1 - p0;
    vec3 e1 = p2 - p1;
    vec3 e2 = p0 - p2;

    float xym = sign(n.z);

    vec2 ne0xy = vec2(-e0.y, e0.x) * xym;
    float de0xy = -dot(ne0xy, p0.xy) + max(0.0, ext.x * ne0xy.x) + max(0.0, ext.y * ne0xy.y);
    if (dot(ne0xy, low.xy) + de0xy < 0.0) return false;

    vec2 ne1xy = vec2(-e1.y, e1.x) * xym;
    float de1xy = -dot(ne1xy, p1.xy) + max(0.0, ext.x * ne1xy.x) + max(0.0, ext.y * ne1xy.y);
    if (dot(ne1xy, low.xy) + de1xy < 0.0) return false;

    vec2 ne2xy = vec2(-e2.y, e2.x) * xym;
    float de2xy = -dot(ne2xy, p2.xy) + max(0.0, ext.x * ne2xy.x) + max(0.0, ext.y * ne2xy.y);
    if (dot(ne2xy, low.xy) + de2xy < 0.0) return false;

    float yzm = sign(n.x);

    vec2 ne0yz = vec2(-e0.z, e0.y) * yzm;
    float de0yz = -dot(ne0yz, p0.yz) + max(0.0, ext.y * ne0yz.x) + max(0.0, ext.z * ne0yz.y);
    if (dot(ne0yz, low.yz) + de0yz < 0.0) return false;

    vec2 ne1yz = vec2(-e1.z, e1.y) * yzm;
    float de1yz = -dot(ne1yz, p1.yz) + max(0.0, ext.y * ne1yz.x) + max(0.0, ext.z * ne1yz.y);
    if (dot(ne1yz, low.yz) + de1yz < 0.0) return false;

    vec2 ne2yz = vec2(-e2.z, e2.y) * yzm;
    float de2yz = -dot(ne2yz, p2.yz) + max(0.0, ext.y * ne2yz.x) + max(0.0, ext.z * ne2yz.y);
    if (dot(ne2yz, low.yz) + de2yz < 0.0) return false;

    float zxm = sign(n.y);

    vec2 ne0zx = vec2(-e0.x, e0.z) * zxm;
    float de0zx = -dot(ne0zx, p0.zx) + max(0.0, ext.z * ne0zx.x) + max(0.0, ext.x * ne0zx.y);
    if (dot(ne0zx, low.zx) + de0zx < 0.0) return false;

    vec2 ne1zx = vec2(-e1.x, e1.z) * zxm;
    float de1zx = -dot(ne1zx, p1.zx) + max(0.0, ext.z * ne1zx.x) + max(0.0, ext.x * ne1zx.y);
    if (dot(ne1zx, low.zx) + de1zx < 0.0) return false;

    vec2 ne2zx = vec2(-e2.x, e2.z) * zxm;
    float de2zx = -dot(ne2zx, p2.zx) + max(0.0, ext.z * ne2zx.x) + max(0.0, ext.x * ne2zx.y);
    if (dot(ne2zx, low.zx) + de2zx < 0.0) return false;

    return true;
}

bool intersectVoxelTriangle2(
    vec3 low, vec3 ext, vec3 p0, vec3 p1, vec3 p2,
    vec3 n, vec3 c,
    vec2 ne0xy, vec2 ne1xy, vec2 ne2xy, float de0xy, float de1xy, float de2xy,
    vec2 ne0yz, vec2 ne1yz, vec2 ne2yz, float de0yz, float de1yz, float de2yz,
    vec2 ne0zx, vec2 ne1zx, vec2 ne2zx, float de0zx, float de1zx, float de2zx
) {
    // https://omnigoat.github.io/2015/03/09/box-triangle-intersection/
    float d1 = dot(n, low + c - p0);
    float d2 = dot(n, low + ext - c - p0);
    if (d1 * d2 > 0.0) return false;

    if (dot(ne0xy, low.xy) + de0xy < 0.0) return false;
    if (dot(ne1xy, low.xy) + de1xy < 0.0) return false;
    if (dot(ne2xy, low.xy) + de2xy < 0.0) return false;
    if (dot(ne0yz, low.yz) + de0yz < 0.0) return false;
    if (dot(ne1yz, low.yz) + de1yz < 0.0) return false;
    if (dot(ne2yz, low.yz) + de2yz < 0.0) return false;
    if (dot(ne0zx, low.zx) + de0zx < 0.0) return false;
    if (dot(ne1zx, low.zx) + de1zx < 0.0) return false;
    if (dot(ne2zx, low.zx) + de2zx < 0.0) return false;

    return true;
}

float triangleArea(vec3 p0, vec3 p1, vec3 p2) {
    return 0.5 * length(cross(p1 - p0, p2 - p0));
}

uint packVoxelPos(ivec4 v) {
    uvec4 u = uvec4(v + 33);
    return (u.x & 0xFFu) |
           ((u.y & 0xFFu) << 8) |
           ((u.z & 0xFFu) << 16) |
           ((u.w & 0xFFu) << 24);
}

void main() {
    uint ix_src_triangle = gl_GlobalInvocationID.x;
    if (ix_src_triangle >= voxelize_data.n_triangles) return;
    uint ix_cascade = gl_GlobalInvocationID.y;

    uint first_index = 3 * ix_src_triangle;
    uint i0 = b_indices.indices[first_index + 0];
    uint i1 = b_indices.indices[first_index + 1];
    uint i2 = b_indices.indices[first_index + 2];

    vec3 p0_model = b_vertices.vertices[i0].position;
    vec3 p1_model = b_vertices.vertices[i1].position;
    vec3 p2_model = b_vertices.vertices[i2].position;

    vec3 p0 = (voxelize_data.model_matrix * vec4(p0_model, 1.0)).xyz;
    vec3 p1 = (voxelize_data.model_matrix * vec4(p1_model, 1.0)).xyz;
    vec3 p2 = (voxelize_data.model_matrix * vec4(p2_model, 1.0)).xyz;
    vec3 normal = normalize(mat3(voxelize_data.normal_matrix) * normalize(
        b_vertices.vertices[i0].normal +
        b_vertices.vertices[i1].normal +
        b_vertices.vertices[i2].normal
    ));

    float voxel_size = voxelSize(ix_cascade);
    float coverage = 0.25 * clamp(triangleArea(p0, p1, p2) / (voxel_size * voxel_size), 0, 4.0);

    // setup for the intersection
    vec3 ext = vec3(voxel_size, voxel_size, voxel_size);
    vec3 n = normalize(cross(p1 - p0, p2 - p0));
    vec3 c = vec3((n.x > 0.0) ? ext.x : 0.0, (n.y > 0.0) ? ext.y : 0.0, (n.z > 0.0) ? ext.z : 0.0);
    vec3 e0 = p1 - p0;
    vec3 e1 = p2 - p1;
    vec3 e2 = p0 - p2;
    float xym = sign(n.z);
    float yzm = sign(n.x);
    float zxm = sign(n.y);
    vec2 ne0xy = vec2(-e0.y, e0.x) * xym;
    vec2 ne1xy = vec2(-e1.y, e1.x) * xym;
    vec2 ne2xy = vec2(-e2.y, e2.x) * xym;
    vec2 ne0yz = vec2(-e0.z, e0.y) * yzm;
    vec2 ne1yz = vec2(-e1.z, e1.y) * yzm;
    vec2 ne2yz = vec2(-e2.z, e2.y) * yzm;
    vec2 ne0zx = vec2(-e0.x, e0.z) * zxm;
    vec2 ne1zx = vec2(-e1.x, e1.z) * zxm;
    vec2 ne2zx = vec2(-e2.x, e2.z) * zxm;
    float de0xy = -dot(ne0xy, p0.xy) + max(0.0, ext.x * ne0xy.x) + max(0.0, ext.y * ne0xy.y);
    float de1xy = -dot(ne1xy, p1.xy) + max(0.0, ext.x * ne1xy.x) + max(0.0, ext.y * ne1xy.y);
    float de2xy = -dot(ne2xy, p2.xy) + max(0.0, ext.x * ne2xy.x) + max(0.0, ext.y * ne2xy.y);
    float de0yz = -dot(ne0yz, p0.yz) + max(0.0, ext.y * ne0yz.x) + max(0.0, ext.z * ne0yz.y);
    float de1yz = -dot(ne1yz, p1.yz) + max(0.0, ext.y * ne1yz.x) + max(0.0, ext.z * ne1yz.y);
    float de2yz = -dot(ne2yz, p2.yz) + max(0.0, ext.y * ne2yz.x) + max(0.0, ext.z * ne2yz.y);
    float de0zx = -dot(ne0zx, p0.zx) + max(0.0, ext.z * ne0zx.x) + max(0.0, ext.x * ne0zx.y);
    float de1zx = -dot(ne1zx, p1.zx) + max(0.0, ext.z * ne1zx.x) + max(0.0, ext.x * ne1zx.y);
    float de2zx = -dot(ne2zx, p2.zx) + max(0.0, ext.z * ne2zx.x) + max(0.0, ext.x * ne2zx.y);
    
    // iterate over the triangle aabb and test for intersection with each voxel
    vec3 lower_bound = min(min(p0, p1), p2);
    vec3 upper_bound = max(max(p0, p1), p2);
    ivec3 voxel_lower_bound = max(ivec3(floor(lower_bound / voxel_size)), ivec3(-33));
    ivec3 voxel_upper_bound = min(ivec3(floor(upper_bound / voxel_size)), ivec3(32));
    for (int x = voxel_lower_bound.x; x <= voxel_upper_bound.x; ++x) {
        for (int y = voxel_lower_bound.y; y <= voxel_upper_bound.y; ++y) {
            for (int z = voxel_lower_bound.z; z <= voxel_upper_bound.z; ++z) {

                vec3 low = voxel_size * vec3(x, y, z);
                if (!intersectVoxelTriangle2(
                    low, ext, p0, p1, p2, n, c,
                    ne0xy, ne1xy, ne2xy, de0xy, de1xy, de2xy,
                    ne0yz, ne1yz, ne2yz, de0yz, de1yz, de2yz,
                    ne0zx, ne1zx, ne2zx, de0zx, de1zx, de2zx
                )) continue;
                // if (!intersectVoxelTriangle(low, ext, p0, p1, p2)) continue;

                // store triangle info
                // we could store data per triangle once instead of per intersection
                // however, if we want to allow for textured models, not just triangle colors
                // and we don't have bindless
                // then it doesn't seem possible to actually light it later
                // so by storing color and normal per intersection
                // we could do the texture lookupts here, and this shader could bind the resource
                // since this is called per mesh (or similar) that works with a bindful renderer
                uint ix_dst_triangle = atomicAdd(b_triangle_counters.n_triangles, 1);
                b_triangle_data.triangles[ix_dst_triangle] = TriangleData(
                    normal,
                    voxelize_data.diffuse, voxelize_data.emissive.rgb, voxelize_data.roughness,
                    coverage
                );

                // store the intersection info
                ivec3 voxel_pos = ivec3(x + 64 * ix_cascade, y, z) + 33;
                b_triangle_isects.isects[ix_dst_triangle] = TriangleIntersection(
                    packVoxelPos(ivec4(x, y, z, ix_cascade)),
                    ix_dst_triangle
                );
            }
        }
    }
}
